# Generated by Django 6.0.2 on 2026-02-25 16:18

import django.db.models.deletion
import scanning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('short_name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('volume', models.PositiveIntegerField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('start_page', models.PositiveIntegerField()),
                ('end_page', models.PositiveIntegerField()),
                ('book_cover', models.ImageField(blank=True, upload_to=scanning.models.cover_upload_path)),
                ('original_pdf', models.FileField(upload_to=scanning.models.scan_upload_path)),
                ('redacted_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('extracted', 'Extracted')], default='uploaded', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='scanning.reporter')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['reporter', 'volume'], name='idx_reporter_volume'), models.Index(fields=['status'], name='idx_status'), models.Index(fields=['uploaded_by'], name='idx_uploaded_by')],
            },
        ),
    ]
