# Generated by Django 6.0.2 on 2026-03-02 23:36

import django.core.validators
import django.db.models.deletion
import scanning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        db_index=True, max_length=20, unique=True
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "number_of_pages",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "start_page",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "end_page",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("full", "Full (Archival version)"),
                            ("opinions", "Opinions only version"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "book_cover",
                    models.FileField(
                        blank=True,
                        upload_to=scanning.models.book_cover_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "gif",
                                    "png",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "original_pdf",
                    models.FileField(
                        upload_to=scanning.models.book_upload_path
                    ),
                ),
                (
                    "redacted_pdf",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "compressed_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scanning.models.compressed_upload_path,
                    ),
                ),
                (
                    "process_output",
                    models.TextField(
                        blank=True,
                        help_text="Verbose output from blackletter pipeline processing.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("extracted", "Extracted"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scans",
                        to="scanning.reporter",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="OpinionScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "original_pdf",
                    models.FileField(
                        upload_to=scanning.models.opinion_pdf_path(
                            "unredacted"
                        )
                    ),
                ),
                (
                    "masked_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scanning.models.opinion_pdf_path("masked"),
                    ),
                ),
                (
                    "redacted_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scanning.models.opinion_pdf_path("redacted"),
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("no_status", "No status"),
                            ("ok", "OK (opinion is correct)"),
                            ("gap", "Gap (missing pages in opinion)"),
                            ("error", "Error"),
                        ],
                        default="no_status",
                        max_length=20,
                    ),
                ),
                (
                    "page_start",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "page_end",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "process_output",
                    models.TextField(
                        blank=True,
                        help_text="Verbose output from blackletter pipeline processing.",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opinion_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opinion_scans",
                        to="scanning.reporter",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opinions",
                        to="scanning.scan",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["reporter", "volume"], name="idx_reporter_volume"
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["status"], name="idx_status"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["uploaded_by"], name="idx_uploaded_by"),
        ),
        migrations.AddConstraint(
            model_name="scan",
            constraint=models.UniqueConstraint(
                fields=("reporter", "volume", "source"),
                name="unique_reporter_volume_source",
                violation_error_message="A scan for this reporter, volume, and source already exists.",
            ),
        ),
        migrations.AddIndex(
            model_name="opinionscan",
            index=models.Index(fields=["scan"], name="idx_opinion_scan"),
        ),
        migrations.AddIndex(
            model_name="opinionscan",
            index=models.Index(
                fields=["reporter", "volume"],
                name="idx_opinion_reporter_volume",
            ),
        ),
        migrations.AddIndex(
            model_name="opinionscan",
            index=models.Index(fields=["status"], name="idx_opinion_status"),
        ),
    ]
