BEGIN;
--
-- Create model Detection
--
CREATE TABLE "scanning_detection" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "page_index" integer NOT NULL CHECK ("page_index" >= 0), "label" varchar(50) NOT NULL, "label_id" smallint NOT NULL, "confidence" double precision NOT NULL, "x0" double precision NOT NULL, "y0" double precision NOT NULL, "x1" double precision NOT NULL, "y1" double precision NOT NULL, "img_width" integer NOT NULL CHECK ("img_width" >= 0), "img_height" integer NOT NULL CHECK ("img_height" >= 0), "model_name" varchar(20) NOT NULL, "model_count" smallint NOT NULL CHECK ("model_count" >= 0), "found_by" text NOT NULL, "active" boolean NOT NULL);
--
-- Create model Issue
--
CREATE TABLE "scanning_issue" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "page_number" integer NULL CHECK ("page_number" >= 0), "check_name" varchar(100) NOT NULL, "severity" varchar(10) NOT NULL, "message" text NOT NULL, "metadata" text NOT NULL);
--
-- Create model PageDeletion
--
CREATE TABLE "scanning_pagedeletion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "pdf_page" integer NOT NULL CHECK ("pdf_page" >= 0));
--
-- Create model PageInsert
--
CREATE TABLE "scanning_pageinsert" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "logical_page_number" integer NOT NULL CHECK ("logical_page_number" >= 0), "image" varchar(100) NOT NULL);
--
-- Create model Volume
--
CREATE TABLE "scanning_volume" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "volume_number" integer NOT NULL CHECK ("volume_number" >= 0), "expected_start_page" integer NULL CHECK ("expected_start_page" >= 0), "expected_end_page" integer NULL CHECK ("expected_end_page" >= 0), "priority" varchar(20) NOT NULL, "queue_status" varchar(20) NOT NULL, "assigned_at" timestamp with time zone NULL, "source_library" varchar(200) NOT NULL, "source_url" varchar(200) NOT NULL, "is_partial" boolean NOT NULL, "expected_parts" integer NULL CHECK ("expected_parts" >= 0), "notes" text NOT NULL);
--
-- Change Meta options on opinionscan
--
-- (no-op)
--
-- Remove constraint unique_reporter_volume_source from model scan
--
ALTER TABLE "scanning_scan" DROP CONSTRAINT "unique_reporter_volume_source";
--
-- Add field caption_page_index to opinionscan
--
ALTER TABLE "scanning_opinionscan" ADD COLUMN "caption_page_index" integer NULL CHECK ("caption_page_index" >= 0);
--
-- Add field has_image to opinionscan
--
ALTER TABLE "scanning_opinionscan" ADD COLUMN "has_image" boolean DEFAULT false NOT NULL;
ALTER TABLE "scanning_opinionscan" ALTER COLUMN "has_image" DROP DEFAULT;
--
-- Add field key_page_index to opinionscan
--
ALTER TABLE "scanning_opinionscan" ADD COLUMN "key_page_index" integer NULL CHECK ("key_page_index" >= 0);
--
-- Add field opinion_order to opinionscan
--
ALTER TABLE "scanning_opinionscan" ADD COLUMN "opinion_order" integer DEFAULT 0 NOT NULL CHECK ("opinion_order" >= 0);
ALTER TABLE "scanning_opinionscan" ALTER COLUMN "opinion_order" DROP DEFAULT;
--
-- Add field checked to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "checked" boolean DEFAULT false NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "checked" DROP DEFAULT;
--
-- Add field has_issues to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "has_issues" boolean DEFAULT false NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "has_issues" DROP DEFAULT;
--
-- Add field has_state_abbrev to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "has_state_abbrev" boolean DEFAULT true NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "has_state_abbrev" DROP DEFAULT;
--
-- Add field margin_rects to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "margin_rects" text DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "margin_rects" DROP DEFAULT;
--
-- Add field missing_pages to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "missing_pages" text DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "missing_pages" DROP DEFAULT;
--
-- Add field ocr_results to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "ocr_results" text DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "ocr_results" DROP DEFAULT;
--
-- Add field opinions_json to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "opinions_json" text DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "opinions_json" DROP DEFAULT;
--
-- Add field output_dir to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "output_dir" varchar(1024) DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "output_dir" DROP DEFAULT;
--
-- Add field page_count to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "page_count" integer DEFAULT 0 NOT NULL CHECK ("page_count" >= 0);
ALTER TABLE "scanning_scan" ALTER COLUMN "page_count" DROP DEFAULT;
--
-- Add field page_map to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "page_map" text DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "page_map" DROP DEFAULT;
--
-- Add field part_label to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "part_label" varchar(20) DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "part_label" DROP DEFAULT;
--
-- Add field progress_current to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "progress_current" integer DEFAULT 0 NOT NULL CHECK ("progress_current" >= 0);
ALTER TABLE "scanning_scan" ALTER COLUMN "progress_current" DROP DEFAULT;
--
-- Add field progress_log to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "progress_log" text DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "progress_log" DROP DEFAULT;
--
-- Add field progress_message to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "progress_message" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "progress_message" DROP DEFAULT;
--
-- Add field progress_total to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "progress_total" integer DEFAULT 0 NOT NULL CHECK ("progress_total" >= 0);
ALTER TABLE "scanning_scan" ALTER COLUMN "progress_total" DROP DEFAULT;
--
-- Add field queued_action to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "queued_action" varchar(30) DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "queued_action" DROP DEFAULT;
--
-- Add field redacted_pdf_path to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "redacted_pdf_path" varchar(1024) DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "redacted_pdf_path" DROP DEFAULT;
--
-- Add field redaction_rects to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "redaction_rects" text DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "redaction_rects" DROP DEFAULT;
--
-- Add field source_library to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "source_library" varchar(200) DEFAULT '' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "source_library" DROP DEFAULT;
--
-- Add field stage to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "stage" varchar(20) DEFAULT 'validate' NOT NULL;
ALTER TABLE "scanning_scan" ALTER COLUMN "stage" DROP DEFAULT;
--
-- Alter field masked_pdf on opinionscan
--
ALTER TABLE "scanning_opinionscan" ALTER COLUMN "masked_pdf" TYPE varchar(512);
--
-- Alter field original_pdf on opinionscan
--
ALTER TABLE "scanning_opinionscan" ALTER COLUMN "original_pdf" TYPE varchar(512);
--
-- Alter field redacted_pdf on opinionscan
--
ALTER TABLE "scanning_opinionscan" ALTER COLUMN "redacted_pdf" TYPE varchar(512);
--
-- Alter field compressed_pdf on scan
--
-- (no-op)
--
-- Alter field end_page on scan
--
ALTER TABLE "scanning_scan" ALTER COLUMN "end_page" DROP NOT NULL;
--
-- Alter field number_of_pages on scan
--
ALTER TABLE "scanning_scan" ALTER COLUMN "number_of_pages" DROP NOT NULL;
--
-- Alter field original_pdf on scan
--
-- (no-op)
--
-- Alter field redacted_pdf on scan
--
-- (no-op)
--
-- Alter field start_page on scan
--
ALTER TABLE "scanning_scan" ALTER COLUMN "start_page" DROP NOT NULL;
--
-- Alter field status on scan
--
-- (no-op)
--
-- Add field scan to detection
--
ALTER TABLE "scanning_detection" ADD COLUMN "scan_id" bigint NOT NULL CONSTRAINT "scanning_detection_scan_id_10ca72c5_fk_scanning_scan_id" REFERENCES "scanning_scan"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "scanning_detection_scan_id_10ca72c5_fk_scanning_scan_id" IMMEDIATE;
--
-- Add field scan to issue
--
ALTER TABLE "scanning_issue" ADD COLUMN "scan_id" bigint NOT NULL CONSTRAINT "scanning_issue_scan_id_f3a02243_fk_scanning_scan_id" REFERENCES "scanning_scan"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "scanning_issue_scan_id_f3a02243_fk_scanning_scan_id" IMMEDIATE;
--
-- Add field scan to pagedeletion
--
ALTER TABLE "scanning_pagedeletion" ADD COLUMN "scan_id" bigint NOT NULL CONSTRAINT "scanning_pagedeletion_scan_id_952d0409_fk_scanning_scan_id" REFERENCES "scanning_scan"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "scanning_pagedeletion_scan_id_952d0409_fk_scanning_scan_id" IMMEDIATE;
--
-- Add field scan to pageinsert
--
ALTER TABLE "scanning_pageinsert" ADD COLUMN "scan_id" bigint NOT NULL CONSTRAINT "scanning_pageinsert_scan_id_ec389d3f_fk_scanning_scan_id" REFERENCES "scanning_scan"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "scanning_pageinsert_scan_id_ec389d3f_fk_scanning_scan_id" IMMEDIATE;
--
-- Add field assigned_to to volume
--
ALTER TABLE "scanning_volume" ADD COLUMN "assigned_to_id" integer NULL CONSTRAINT "scanning_volume_assigned_to_id_074d696d_fk_auth_user_id" REFERENCES "auth_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "scanning_volume_assigned_to_id_074d696d_fk_auth_user_id" IMMEDIATE;
--
-- Add field reporter to volume
--
ALTER TABLE "scanning_volume" ADD COLUMN "reporter_id" bigint NOT NULL CONSTRAINT "scanning_volume_reporter_id_47aae976_fk_scanning_reporter_id" REFERENCES "scanning_reporter"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "scanning_volume_reporter_id_47aae976_fk_scanning_reporter_id" IMMEDIATE;
--
-- Add field volume_obj to scan
--
ALTER TABLE "scanning_scan" ADD COLUMN "volume_obj_id" bigint NULL CONSTRAINT "scanning_scan_volume_obj_id_0fb561e3_fk_scanning_volume_id" REFERENCES "scanning_volume"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "scanning_scan_volume_obj_id_0fb561e3_fk_scanning_volume_id" IMMEDIATE;
--
-- Create index idx_stage on field(s) stage of model scan
--
CREATE INDEX "idx_stage" ON "scanning_scan" ("stage");
--
-- Create index idx_det_scan_page on field(s) scan, page_index of model detection
--
CREATE INDEX "idx_det_scan_page" ON "scanning_detection" ("scan_id", "page_index");
--
-- Create index idx_det_scan_label on field(s) scan, label of model detection
--
CREATE INDEX "idx_det_scan_label" ON "scanning_detection" ("scan_id", "label");
--
-- Create index idx_det_scan_active on field(s) scan, active of model detection
--
CREATE INDEX "idx_det_scan_active" ON "scanning_detection" ("scan_id", "active");
--
-- Alter unique_together for pagedeletion (1 constraint(s))
--
ALTER TABLE "scanning_pagedeletion" ADD CONSTRAINT "scanning_pagedeletion_scan_id_pdf_page_7d36bc20_uniq" UNIQUE ("scan_id", "pdf_page");
--
-- Alter unique_together for pageinsert (1 constraint(s))
--
ALTER TABLE "scanning_pageinsert" ADD CONSTRAINT "scanning_pageinsert_scan_id_logical_page_number_535a5337_uniq" UNIQUE ("scan_id", "logical_page_number");
--
-- Create constraint unique_volume_reporter_number on model volume
--
ALTER TABLE "scanning_volume" ADD CONSTRAINT "unique_volume_reporter_number" UNIQUE ("reporter_id", "volume_number");
CREATE INDEX "scanning_detection_date_created_3886cc54" ON "scanning_detection" ("date_created");
CREATE INDEX "scanning_detection_date_modified_a543f524" ON "scanning_detection" ("date_modified");
CREATE INDEX "scanning_detection_page_index_d6e463db" ON "scanning_detection" ("page_index");
CREATE INDEX "scanning_issue_date_created_3a8252cd" ON "scanning_issue" ("date_created");
CREATE INDEX "scanning_issue_date_modified_bfa902c5" ON "scanning_issue" ("date_modified");
CREATE INDEX "scanning_pagedeletion_date_created_8c1c3c39" ON "scanning_pagedeletion" ("date_created");
CREATE INDEX "scanning_pagedeletion_date_modified_071619c9" ON "scanning_pagedeletion" ("date_modified");
CREATE INDEX "scanning_pageinsert_date_created_a08608e2" ON "scanning_pageinsert" ("date_created");
CREATE INDEX "scanning_pageinsert_date_modified_2ec7a10d" ON "scanning_pageinsert" ("date_modified");
CREATE INDEX "scanning_volume_date_created_43176901" ON "scanning_volume" ("date_created");
CREATE INDEX "scanning_volume_date_modified_cdfe0426" ON "scanning_volume" ("date_modified");
CREATE INDEX "scanning_detection_scan_id_10ca72c5" ON "scanning_detection" ("scan_id");
CREATE INDEX "scanning_issue_scan_id_f3a02243" ON "scanning_issue" ("scan_id");
CREATE INDEX "scanning_pagedeletion_scan_id_952d0409" ON "scanning_pagedeletion" ("scan_id");
CREATE INDEX "scanning_pageinsert_scan_id_ec389d3f" ON "scanning_pageinsert" ("scan_id");
CREATE INDEX "scanning_volume_assigned_to_id_074d696d" ON "scanning_volume" ("assigned_to_id");
CREATE INDEX "scanning_volume_reporter_id_47aae976" ON "scanning_volume" ("reporter_id");
CREATE INDEX "scanning_scan_volume_obj_id_0fb561e3" ON "scanning_scan" ("volume_obj_id");
COMMIT;