# Generated by Django 6.0.2 on 2026-03-24 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                ("page_index", models.PositiveIntegerField(db_index=True)),
                ("label", models.CharField(max_length=50)),
                ("label_id", models.SmallIntegerField()),
                ("confidence", models.FloatField()),
                ("x0", models.FloatField()),
                ("y0", models.FloatField()),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                ("img_width", models.PositiveIntegerField(default=0)),
                ("img_height", models.PositiveIntegerField(default=0)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("model_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "found_by",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="JSON: per-model confidence breakdown.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["page_index", "y0", "x0"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("check_name", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="error",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "metadata",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="JSON for structured data (e.g. suppression info).",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number", "severity"],
            },
        ),
        migrations.CreateModel(
            name="LLMScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "masked_pdf",
                    models.FileField(blank=True, null=True, upload_to="llm/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent to LLM"),
                            ("extracted", "Extracted"),
                            ("merged", "Merged"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("cost_cents", models.PositiveIntegerField(default=0)),
                ("raw_response", models.TextField(blank=True, default="")),
                ("extracted_text", models.TextField(blank=True, default="")),
                (
                    "extracted_metadata",
                    models.TextField(blank=True, default=""),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="PageDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "pdf_page",
                    models.PositiveIntegerField(
                        help_text="1-based PDF page number."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageInsert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                ("logical_page_number", models.PositiveIntegerField()),
                ("image", models.FileField(upload_to="page_inserts/")),
            ],
        ),
        migrations.AlterModelOptions(
            name="opinionscan",
            options={"ordering": ["opinion_order", "-date_created"]},
        ),
        migrations.AddField(
            model_name="opinionscan",
            name="caption_page_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opinionscan",
            name="has_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opinionscan",
            name="key_page_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opinionscan",
            name="opinion_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scan",
            name="has_issues",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scan",
            name="has_state_abbrev",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="missing_pages",
            field=models.TextField(
                blank=True,
                default="",
                help_text="JSON: list of missing logical page numbers.",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="ocr_results",
            field=models.TextField(
                blank=True,
                default="",
                help_text="JSON: per-page OCR detection results.",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="opinions_json",
            field=models.TextField(
                blank=True,
                default="",
                help_text="JSON: opinion boundary data.",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="output_dir",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="scan",
            name="page_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="page_map",
            field=models.TextField(
                blank=True, default="", help_text="JSON: viewer page sequence."
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="progress_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="progress_log",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Captured stdout from processing.",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="progress_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="scan",
            name="progress_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="redacted_pdf_path",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="scan",
            name="stage",
            field=models.CharField(
                choices=[
                    ("validate", "Validate"),
                    ("process", "Process"),
                    ("approved", "Approved"),
                ],
                default="validate",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("pending_review", "Pending Review"),
                    ("approved", "Approved"),
                    ("extracted", "Extracted"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["stage"], name="idx_stage"),
        ),
        migrations.AddField(
            model_name="detection",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="scanning.scan",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="scanning.scan",
            ),
        ),
        migrations.AddField(
            model_name="llmscan",
            name="opinions",
            field=models.ManyToManyField(
                blank=True, related_name="llm_scans", to="scanning.opinionscan"
            ),
        ),
        migrations.AddField(
            model_name="llmscan",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_scans",
                to="scanning.scan",
            ),
        ),
        migrations.AddField(
            model_name="pagedeletion",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deletions",
                to="scanning.scan",
            ),
        ),
        migrations.AddField(
            model_name="pageinsert",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inserts",
                to="scanning.scan",
            ),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["scan", "page_index"], name="idx_det_scan_page"
            ),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["scan", "label"], name="idx_det_scan_label"
            ),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["scan", "active"], name="idx_det_scan_active"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pagedeletion",
            unique_together={("scan", "pdf_page")},
        ),
        migrations.AlterUniqueTogether(
            name="pageinsert",
            unique_together={("scan", "logical_page_number")},
        ),
    ]
