# Generated by Django 6.0.3 on 2026-04-02 20:38

import django.core.validators
import django.db.models.deletion
import scanning.models
import scanning.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                ("page_index", models.PositiveIntegerField(db_index=True)),
                ("label", models.CharField(max_length=50)),
                ("label_id", models.SmallIntegerField()),
                ("confidence", models.FloatField()),
                ("x0", models.FloatField()),
                ("y0", models.FloatField()),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                ("img_width", models.PositiveIntegerField(default=0)),
                ("img_height", models.PositiveIntegerField(default=0)),
                ("model_name", models.CharField(blank=True, choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large"), ("manual", "Manual")], default="", max_length=20)),
                ("model_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "found_by",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Per-model confidence breakdown.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["page_index", "y0", "x0"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("check_name", models.CharField(choices=[("no_page_number", "No page number detected"), ("missing_page", "Missing page in sequence"), ("duplicate_page", "Duplicate page number"), ("backward_page", "Page number goes backward"), ("large_gap", "Large gap in page numbers"), ("suspicious_reading", "Suspicious OCR reading"), ("page_range", "Page range detected"), ("mislabeled_document", "Mislabeled document type"), ("auto_corrected", "Auto-corrected page number"), ("blank_page", "Blank page detected"), ("orientation", "Page orientation issue"), ("process_flag", "User-flagged issue"), ("suppress_detection", "Suppress a detection"), ("add_detection", "Add a detection"), ("approve_detection", "Approve a detection")], max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="error",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data (e.g. suppression info).",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number", "severity"],
            },
        ),
        migrations.CreateModel(
            name="PageDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "pdf_page",
                    models.PositiveIntegerField(help_text="1-based PDF page number."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageInsert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                ("logical_page_number", models.PositiveIntegerField()),
                (
                    "image",
                    models.FileField(
                        storage=scanning.storage.LocalProcessingStorage(),
                        upload_to="page_inserts/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "volume_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "expected_start_page",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "expected_end_page",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("backlog", "Backlog"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "queue_status",
                    models.CharField(
                        choices=[
                            ("needs_scanning", "Needs Scanning"),
                            ("assigned", "Assigned"),
                            ("scanning", "Scanning"),
                            ("scanned", "Scanned"),
                            ("complete", "Complete"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="needs_scanning",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_library",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("source_url", models.URLField(blank=True, default="")),
                (
                    "is_partial",
                    models.BooleanField(
                        default=False,
                        help_text="Volume is split into multiple parts (e.g. books A/B or advance sheets).",
                    ),
                ),
                (
                    "expected_parts",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many scans make up this volume.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["reporter", "volume_number"],
            },
        ),
        migrations.AlterModelOptions(
            name="opinionscan",
            options={"ordering": ["opinion_order", "-date_created"]},
        ),
        migrations.RemoveConstraint(
            model_name="scan",
            name="unique_reporter_volume_source",
        ),
        migrations.AddField(
            model_name="opinionscan",
            name="caption_page_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opinionscan",
            name="has_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opinionscan",
            name="key_page_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opinionscan",
            name="opinion_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="has_state_abbrev",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="margin_rects",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Per-page margin rects in PDF points.",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="missing_pages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of missing logical page numbers.",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="ocr_results",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Per-page OCR detection results.",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="opinions_json",
            field=models.JSONField(
                blank=True, default=list, help_text="Opinion boundary data."
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="page_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="page_map",
            field=models.JSONField(
                blank=True, default=list, help_text="Viewer page sequence."
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="part_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Part identifier (e.g. 'A', 'B', '3' for advance sheets).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="progress_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="progress_log",
            field=models.TextField(
                blank=True, default="", help_text="Captured stdout from processing."
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="progress_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="scan",
            name="progress_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="queued_action",
            field=models.CharField(
                blank=True,
                choices=[("full_pipeline", "Full Pipeline"), ("validate", "Validate"), ("detect", "Detect"), ("reprocess", "Reprocess"), ("generate_files", "Generate Files")],
                default="",
                help_text="Action for the daemon to run when status is queued.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="redacted_pdf_path",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="scan",
            name="redaction_rects",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Per-page redaction rects in image pixels.",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="source_library",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="scan",
            name="stage",
            field=models.CharField(
                choices=[
                    ("validate", "Validate"),
                    ("process", "Process"),
                    ("approved", "Approved"),
                ],
                default="validate",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="opinionscan",
            name="masked_pdf",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=scanning.storage.LocalProcessingStorage(),
                upload_to=scanning.models.opinion_pdf_path("masked"),
            ),
        ),
        migrations.AlterField(
            model_name="opinionscan",
            name="original_pdf",
            field=models.FileField(
                max_length=512,
                storage=scanning.storage.LocalProcessingStorage(),
                upload_to=scanning.models.opinion_pdf_path("unredacted"),
            ),
        ),
        migrations.AlterField(
            model_name="opinionscan",
            name="redacted_pdf",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=scanning.storage.LocalProcessingStorage(),
                upload_to=scanning.models.opinion_pdf_path("redacted"),
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="compressed_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=scanning.storage.LocalProcessingStorage(),
                upload_to=scanning.models.compressed_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="end_page",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="number_of_pages",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="original_pdf",
            field=models.FileField(
                blank=True, upload_to=scanning.models.book_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="redacted_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=scanning.storage.LocalProcessingStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="start_page",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("pending_review", "Pending Review"),
                    ("approved", "Approved"),
                    ("extracted", "Extracted"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="detection",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="scanning.scan",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="scanning.scan",
            ),
        ),
        migrations.AddField(
            model_name="pagedeletion",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deletions",
                to="scanning.scan",
            ),
        ),
        migrations.AddField(
            model_name="pageinsert",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inserts",
                to="scanning.scan",
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_volumes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="volumes",
                to="scanning.reporter",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="volume_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="The Volume this scan belongs to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scans",
                to="scanning.volume",
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["stage"], name="idx_stage"),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["scan", "page_index"], name="idx_det_scan_page"),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["scan", "label"], name="idx_det_scan_label"),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["scan", "active"], name="idx_det_scan_active"),
        ),
        migrations.AlterUniqueTogether(
            name="pagedeletion",
            unique_together={("scan", "pdf_page")},
        ),
        migrations.AlterUniqueTogether(
            name="pageinsert",
            unique_together={("scan", "logical_page_number")},
        ),
        migrations.AddConstraint(
            model_name="volume",
            constraint=models.UniqueConstraint(
                fields=("reporter", "volume_number"),
                name="unique_volume_reporter_number",
            ),
        ),
        migrations.AddField(
            model_name='scan',
            name='s3_path',
            field=models.CharField(blank=True, default='', help_text='Relative S3 key prefix for approved files, e.g. approved/a3d/218/1/', max_length=512),
        ),
        migrations.AddField(
            model_name='scan',
            name='s3_uploaded',
            field=models.BooleanField(default=False, help_text='Whether final files have been uploaded to S3.'),
        ),
    ]
