# Generated by Django 6.0.3 on 2026-05-08 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0003_scan_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='number_of_pages',
            field=models.PositiveIntegerField(blank=True, help_text="Canonical page count of the printed volume, entered by the scanner. Excludes withdrawn opinions and may not equal the uploaded PDF's length when the volume contains special pages (e.g. 1390A, 1390B) or skipped page ranges. See page_count for the actual PDF length.", null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scan',
            name='page_count',
            field=models.PositiveIntegerField(default=0, help_text='Actual page count of the uploaded PDF file. Auto-populated by the processing pipeline and updated when pages are inserted or deleted. May differ from number_of_pages when the printed volume has special pages or skipped ranges.'),
        ),
    ]
