# Generated by Django 6.0.3 on 2026-05-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0003_scan_retry_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='number_of_pages',
        ),
    ]
