# Generated by Django 6.0.2 on 2026-03-25 12:59

import scanning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0004_alter_scan_end_page_alter_scan_number_of_pages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinionscan",
            name="masked_pdf",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=scanning.models.opinion_pdf_path("masked"),
            ),
        ),
        migrations.AlterField(
            model_name="opinionscan",
            name="original_pdf",
            field=models.FileField(
                max_length=512, upload_to=scanning.models.opinion_pdf_path("unredacted")
            ),
        ),
        migrations.AlterField(
            model_name="opinionscan",
            name="redacted_pdf",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=scanning.models.opinion_pdf_path("redacted"),
            ),
        ),
    ]
