# Generated by Django 6.0.3 on 2026-05-14 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('scanning', '0004_alter_scan_number_of_pages_alter_scan_page_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinionscan',
            name='masked_pdf',
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('page_index', models.PositiveIntegerField(help_text='0-based, matching ``Detection.page_index``. The PDF filename is ``llm/page_{page_index + 1:04d}.pdf``.')),
                ('book_page', models.CharField(blank=True, default='', help_text="Visible page number printed on this page of the book. Usually one integer like '687'; rarely a range like '678-686' when a single PDF page collapses several book pages.", max_length=32)),
                ('pdf_path', models.CharField(blank=True, default='', help_text='Relative to ``scan.output_dir``, e.g. ``llm/page_0001.pdf``.', max_length=512)),
                ('xml_content', models.TextField(blank=True, default='', help_text='Extracted XML for this page.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted to batch'), ('extracted', 'Extracted'), ('failed', 'Failed'), ('prompt_blocked', 'Blocked at prompt level'), ('response_blocked', 'Blocked at response level'), ('recitation_blocked', 'Blocked by recitation filter')], default='pending', max_length=32)),
                ('extracted_by', models.CharField(blank=True, choices=[('LLM', 'LLM'), ('ocr-fallback', 'Local OCR fallback'), ('human', 'Human review'), ('blank-auto', 'Blank page (auto)')], default='', max_length=32)),
                ('needs_review', models.BooleanField(default=False, help_text='Set when the OCR fallback ran or the model output looked suspicious. Triage view filters by this.')),
                ('expected_opinion_starts', models.PositiveIntegerField(default=0)),
                ('expected_opinion_ends', models.PositiveIntegerField(default=0)),
                ('detections', models.JSONField(blank=True, default=list, help_text='All YOLO detections on this page, filtered from ``detections.json`` at sync time.')),
                ('is_blank', models.BooleanField(default=False, help_text='Body is entirely covered by headnote redactions.')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='scanning.scan')),
                ('user_prompt', models.ForeignKey(blank=True, help_text='Current user prompt for this page. A tweaked prompt is a new Prompt row; this FK is repointed and the prior Prompt stays as history.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='ai.prompt')),
            ],
            options={
                'ordering': ('scan', 'page_index'),
                'indexes': [models.Index(fields=['scan', 'page_index'], name='idx_page_scan_idx'), models.Index(fields=['status'], name='idx_page_status'), models.Index(fields=['scan', 'needs_review'], name='idx_page_review')],
                'constraints': [models.UniqueConstraint(fields=('scan', 'page_index'), name='unique_page_scan_index')],
            },
        ),
    ]
