# Generated by Django 6.0.2 on 2026-03-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0005_alter_opinionscan_masked_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmscan",
            name="masked_pdf",
            field=models.FileField(
                blank=True, max_length=512, null=True, upload_to="llm/"
            ),
        ),
    ]
