# Generated by Django 6.0.3 on 2026-07-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0005_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='interruption_count',
            field=models.PositiveIntegerField(default=0, help_text='Times the daemon was killed or timed out while this scan was PROCESSING and re-queued it. Distinct from retry_count: these are infra interruptions (deploys, evictions), not scan failures.'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('extracted', 'Extracted'), ('error', 'Error'), ('error_max_retries', 'Error (retry cap hit)'), ('error_interrupted', 'Error (interrupted too often)'), ('cancelled', 'Cancelled')], default='uploaded', max_length=20),
        ),
    ]
