# Generated by Django 6.0.2 on 2026-03-25 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0006_alter_llmscan_masked_pdf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "volume_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "expected_start_page",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "expected_end_page",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("backlog", "Backlog"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "queue_status",
                    models.CharField(
                        choices=[
                            ("needs_scanning", "Needs Scanning"),
                            ("assigned", "Assigned"),
                            ("scanning", "Scanning"),
                            ("scanned", "Scanned"),
                            ("complete", "Complete"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="needs_scanning",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_library",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("source_url", models.URLField(blank=True, default="")),
                (
                    "is_partial",
                    models.BooleanField(
                        default=False,
                        help_text="Volume is split into multiple parts (e.g. books A/B or advance sheets).",
                    ),
                ),
                (
                    "expected_parts",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many scans make up this volume.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["reporter", "volume_number"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="scan",
            name="unique_reporter_volume_source",
        ),
        migrations.AddField(
            model_name="scan",
            name="part_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Part identifier (e.g. 'A', 'B', '3' for advance sheets).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_volumes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="volumes",
                to="scanning.reporter",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="volume_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="The Volume this scan belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to="scanning.volume",
            ),
        ),
        migrations.AddConstraint(
            model_name="scan",
            constraint=models.UniqueConstraint(
                fields=("reporter", "volume", "source", "start_page"),
                name="unique_reporter_volume_source_start",
                violation_error_message="A scan for this reporter, volume, source, and start page already exists.",
            ),
        ),
        migrations.RemoveField(
            model_name="scan",
            name="assigned_at",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="queue_status",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="source_url",
        ),
        migrations.AddConstraint(
            model_name="volume",
            constraint=models.UniqueConstraint(
                fields=("reporter", "volume_number"),
                name="unique_volume_reporter_number",
            ),
        ),
    ]
