# Generated by Django 6.0.2 on 2026-03-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0007_volume_remove_scan_unique_reporter_volume_source_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scan",
            name="unique_reporter_volume_source_start",
        ),
    ]
