# Generated by Django 6.0.3 on 2026-08-11 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0007_pendingupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('stage', models.CharField(choices=[('detect', 'Detect (YOLO)'), ('analyze', 'Analyze (page numbers)'), ('extract', 'Extract text'), ('tiebreak', 'Tiebreak disputed reads')], max_length=20)),
                ('engine', models.CharField(choices=[('blackletter', 'blackletter (YOLO + PaddleOCR)'), ('dots_mocr', 'dots.mocr'), ('mistral_ocr', 'Mistral OCR'), ('surya', 'Surya'), ('lighton_ocr', 'LightOnOCR')], max_length=32)),
                ('provider', models.CharField(choices=[('runpod', 'RunPod Serverless'), ('mistral', 'Mistral API')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending submit'), ('submitted', 'Submitted'), ('in_queue', 'In queue'), ('in_progress', 'In progress'), ('completed', 'Completed (result not yet applied)'), ('consumed', 'Result applied'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired (result lost)')], default='pending', max_length=20)),
                ('run', models.PositiveSmallIntegerField(default=1, help_text="Stage-run generation. Re-running a stage (a re-validate, a reprocess) creates rows at the next run number and keeps the previous run as history, while retrying a single shard mutates its row. Scoped per engine, not per stage: the live jobs of one engine are its rows at that engine's max(run), and a stage's live jobs are the union of those, so re-running one engine of a multi-engine stage cannot hide another engine's rows from the barrier.")),
                ('attempt', models.PositiveSmallIntegerField(default=1, help_text="Which submission of this row is in flight, incremented on every resubmission whatever the reason, and carried in ``result_key`` so two attempts of one shard never write to the same object. Deliberately not derived from retry_count: that accounts for why a job was resubmitted and can stay flat across one (a daemon restart), and a key reused across attempts lets an abandoned worker's late upload be harvested as the current attempt's output.")),
                ('external_id', models.CharField(blank=True, default='', help_text="The provider's job id, set on submit and kept after the terminal state for auditing and billing lookups. This is what lets a restarted daemon reattach to a job that is still running instead of paying for it twice.", max_length=128)),
                ('shard_index', models.PositiveIntegerField(default=0, help_text="Position of this job within its target's fan-out, and part of the unique key. Zero of one for the normal case, since an opinion PDF is read whole; the split exists so a document too large for one request can be divided without a schema change.")),
                ('shard_count', models.PositiveIntegerField(default=1, help_text="How many jobs this target's fan-out was split into.")),
                ('input_key', models.CharField(blank=True, default='', help_text='S3 key of the exact bytes sent: an opinion PDF for the post-generation stages, the volume for the earlier ones. Recorded because opinion PDFs are regenerated and renamed when pairing changes, so the FK alone does not say which file version was actually read.', max_length=1024)),
                ('source_digest', models.CharField(blank=True, default='', help_text='Digest of the document at ``input_key`` when it was sent. Provenance rather than a reference, so it answers the question the FK cannot: whether an extraction still describes the current file, or the opinion has been regenerated underneath it and has to be read again.', max_length=64)),
                ('input_manifest', models.JSONField(blank=True, default=dict, help_text='Provider-shaped description of the work when a page range is not enough: the list of boxes for a tiebreak read, per-job tuning overrides.')),
                ('result_key', models.CharField(blank=True, default='', help_text="S3 key the worker uploads its output to, assigned by us at submit time and handed over as a presigned PUT. Must be scoped to run, shard, and attempt, and never overwritten: that is what makes a lost status response recoverable with a head_object, and what stops the probe from harvesting another run's or another attempt's output.", max_length=1024)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the job was handed to the provider. Also the reference point for deciding whether an object at ``result_key`` belongs to this attempt.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, help_text="Wall-clock ceiling stamped at submit: a base timeout plus an allowance for this job's pages. Per job rather than per scan so one wedged shard is cancelled and resubmitted without stalling its siblings.", null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Transient failures retried for this job.')),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_meta', models.JSONField(blank=True, default=dict, help_text='Everything about the run that is diagnostic rather than structural: which endpoint served it, worker metadata, timings, sizes, cost, and an append-only ``attempts`` list of prior attempts so mutating this row on retry still keeps its history.')),
                ('opinion', models.ForeignKey(blank=True, help_text="The opinion PDF this job read, for the post-generation stages. Null for the volume-level stages that run before review, when no opinion exists yet. Must belong to ``scan``.\n\nCASCADE, not SET_NULL, because an orphaned extract row would break the invariant that an opinion-level stage has an opinion, and would leave the stage barrier counting a row with no target. Note the consequence: ``run_generate_files`` deletes and recreates a scan's OpinionScan rows, so regenerating files discards every extraction job with them. That is right when the opinion actually changed, and wasteful when it did not, which is why preserving unchanged opinion rows (issue #165) has to land before we pay for hundreds of jobs a volume.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scanning.opinionscan')),
                ('scan', models.ForeignKey(help_text="The volume this work belongs to, set even on a job whose target is a single opinion. Denormalized deliberately: 'has this scan anything in flight' is the daemon's most frequent question and must not need a join, and it keeps the cascade rooted at the scan.", on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scanning.scan')),
            ],
            options={
                'ordering': ['scan', 'stage', 'run', 'engine', 'opinion', 'shard_index'],
                'indexes': [models.Index(fields=['status', 'deadline'], name='idx_job_status_deadline'), models.Index(fields=['scan', 'stage', 'run'], name='idx_job_scan_stage_run'), models.Index(fields=['scan', 'status'], name='idx_job_scan_status'), models.Index(fields=['opinion', 'stage', 'status'], name='idx_job_opinion_stage'), models.Index(fields=['external_id'], name='idx_job_external_id')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('opinion__isnull', True)), fields=('scan', 'stage', 'engine', 'run', 'shard_index'), name='unique_volume_job_per_engine_run'), models.UniqueConstraint(condition=models.Q(('opinion__isnull', False)), fields=('opinion', 'stage', 'engine', 'run', 'shard_index'), name='unique_opinion_job_per_engine_run'), models.CheckConstraint(condition=models.Q(models.Q(('opinion__isnull', False), ('stage__in', ('extract', 'tiebreak'))), models.Q(models.Q(('stage__in', ('extract', 'tiebreak')), _negated=True), ('opinion__isnull', True)), _connector='OR'), name='job_opinion_matches_stage'), models.CheckConstraint(condition=models.Q(('shard_index__lt', models.F('shard_count'))), name='job_shard_index_within_count'), models.CheckConstraint(condition=models.Q(('run__gte', 1)), name='job_run_positive')],
            },
        ),
    ]
