# Generated by Django 6.0.3 on 2026-08-13 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0007_pendingupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('stage', models.CharField(choices=[('convert', 'Convert to bitonal'), ('detect', 'Detect (YOLO)'), ('analyze', 'Analyze (page numbers)'), ('extract', 'Extract text'), ('tiebreak', 'Tiebreak disputed reads')], max_length=20)),
                ('engine', models.CharField(choices=[('blackletter', 'blackletter (YOLO + PaddleOCR)'), ('bitonal', 'Bitonal conversion'), ('dots_mocr', 'dots.mocr'), ('mistral_ocr', 'Mistral OCR'), ('surya', 'Surya'), ('lighton_ocr', 'LightOnOCR')], max_length=32)),
                ('provider', models.CharField(choices=[('runpod', 'RunPod Serverless'), ('mistral', 'Mistral API'), ('doctor', 'Doctor')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending submit'), ('submitted', 'Submitted'), ('in_queue', 'In queue'), ('in_progress', 'In progress'), ('completed', 'Completed (result not yet applied)'), ('consumed', 'Result applied'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired (result lost)')], default='pending', max_length=20)),
                ('run', models.PositiveSmallIntegerField(default=1, help_text="Stage-run generation. Re-running a stage (a re-validate, a reprocess) creates rows at the next run number and keeps the previous run as history; retrying a single shard mutates its row instead. Scoped per engine, not per stage: an engine's live jobs are its rows at its own max(run), and a stage's are the union of those, so re-running one engine of a multi-engine stage cannot hide another engine's rows from the barrier.")),
                ('attempt', models.PositiveSmallIntegerField(default=1, help_text="Which submission of this row is in flight, incremented on every resubmission whatever the reason, and carried in ``result_key`` so two attempts of one shard never write to the same object. Not derived from retry_count, which accounts for why a job was resubmitted and can stay flat across one (a daemon restart). A key reused across attempts lets an abandoned worker's late upload be harvested as the current attempt's output.")),
                ('external_id', models.CharField(blank=True, default='', help_text="The provider's job id, set on submit and kept after the terminal state for auditing and billing lookups. Lets a restarted daemon reattach to a job that is still running instead of paying for it twice.", max_length=128)),
                ('shard_index', models.PositiveIntegerField(default=0, help_text="Position of this job within its target's fan-out, and part of the unique key. Splitting a volume into page ranges and running them at once is how we make a slow full-volume pass finish quickly, and it is the normal case for bitonal and dots.mocr rather than an escape hatch for oversized documents. Zero of one when the target is read whole, as an opinion PDF is.")),
                ('shard_count', models.PositiveIntegerField(default=1, help_text="How many jobs this target's fan-out was split into; one when the target is read whole.")),
                ('input_key', models.CharField(blank=True, default='', help_text='S3 key of the exact bytes sent: an opinion PDF for the post-generation stages, the volume or one of its shards for the earlier ones. Recorded because opinion PDFs are regenerated and renamed when pairing changes, so the FK alone does not say which file version was read.', max_length=1024)),
                ('input_hash', models.CharField(blank=True, default='', help_text='Hash of the document at ``input_key`` when it was sent. Answers what the FK cannot: whether an extraction still describes the current file, or the opinion has been regenerated underneath it and has to be read again.', max_length=64)),
                ('input_manifest', models.JSONField(blank=True, default=dict, help_text='Provider-shaped description of the work, for jobs an input key does not fully describe. A tiebreak read is a list of regions rather than a whole document:\n\n{"crops": [{"key": "page_0007_84_132_1620_230", "page_index": 7, "bbox": [84, 132, 1620, 230]}]}\n\nand any job may carry per-job tuning overrides, such as {"dpi": 400}.')),
                ('result_key', models.CharField(blank=True, default='', help_text="S3 key the worker uploads its output to, assigned by us at submit time and handed over as a presigned PUT. Scoped to run, shard, and attempt, and never overwritten: that makes a lost status response recoverable with a head_object, and stops the probe harvesting another run's or another attempt's output.", max_length=1024)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the job was handed to the provider. Also the reference point for deciding whether an object at ``result_key`` belongs to this attempt.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, help_text="Wall-clock ceiling stamped at submit: a base timeout plus an allowance for this job's pages. Per job rather than per scan so one wedged shard is cancelled and resubmitted without stalling its siblings.", null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Transient failures retried for this job.')),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_meta', models.JSONField(blank=True, default=dict, help_text='Diagnostic rather than structural: which endpoint served it, worker metadata, timings, sizes, cost, and an append-only ``attempts`` list of prior attempts so mutating this row on retry still keeps its history.')),
                ('opinion', models.ForeignKey(blank=True, help_text="The opinion PDF this job read, for the post-generation stages. Null for the volume-level stages, which run before any opinion exists. Must belong to ``scan``.\n\nCASCADE rather than SET_NULL: an orphaned extract row would break the invariant that an opinion-level stage has an opinion, and would leave the stage barrier counting a row with no target. The consequence is that ``run_generate_files`` deletes and recreates a scan's OpinionScan rows, so regenerating files discards every extraction job with them. Right when the opinion changed, wasteful when it did not, which is why preserving unchanged opinion rows (issue #165) has to land before we pay for hundreds of jobs a volume.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scanning.opinionscan')),
                ('scan', models.ForeignKey(help_text="The volume this work belongs to, set even when the target is a single opinion. Denormalized so 'has this scan anything in flight', the daemon's most frequent question, needs no join, and so the cascade is rooted at the scan.", on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scanning.scan')),
            ],
            options={
                'ordering': ['scan', 'stage', 'run', 'engine', 'opinion', 'shard_index'],
                'indexes': [models.Index(fields=['status', 'deadline'], name='idx_job_status_deadline'), models.Index(fields=['scan', 'stage', 'run'], name='idx_job_scan_stage_run'), models.Index(fields=['scan', 'status'], name='idx_job_scan_status'), models.Index(fields=['opinion', 'stage', 'status'], name='idx_job_opinion_stage'), models.Index(fields=['external_id'], name='idx_job_external_id')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('opinion__isnull', True)), fields=('scan', 'stage', 'engine', 'run', 'shard_index'), name='unique_volume_job_per_engine_run'), models.UniqueConstraint(condition=models.Q(('opinion__isnull', False)), fields=('opinion', 'stage', 'engine', 'run', 'shard_index'), name='unique_opinion_job_per_engine_run'), models.CheckConstraint(condition=models.Q(models.Q(('opinion__isnull', False), ('stage__in', ('extract', 'tiebreak'))), models.Q(models.Q(('stage__in', ('extract', 'tiebreak')), _negated=True), ('opinion__isnull', True)), _connector='OR'), name='job_opinion_matches_stage'), models.CheckConstraint(condition=models.Q(('shard_index__lt', models.F('shard_count'))), name='job_shard_index_within_count'), models.CheckConstraint(condition=models.Q(('run__gte', 1)), name='job_run_positive')],
            },
        ),
    ]
