# Generated by Django 6.0.3 on 2026-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0007_pendingupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='runpod_job_action',
            field=models.CharField(blank=True, default='', help_text='Action the in-flight RunPod job is running (detect or analyze), so reattach knows which pipeline stage the job id belongs to.', max_length=16),
        ),
        migrations.AddField(
            model_name='scan',
            name='runpod_job_id',
            field=models.CharField(blank=True, default='', help_text='Id of the RunPod job currently in flight for this scan. Set when a job is submitted, cleared when it reaches a terminal state. Persisted so that if the daemon is killed mid-poll, the next tick can reattach to the running job instead of submitting a duplicate (issue #127).', max_length=128),
        ),
        migrations.AddField(
            model_name='scan',
            name='runpod_job_submitted_at',
            field=models.DateTimeField(blank=True, help_text="When the in-flight RunPod job was submitted. Used to skip reattach once the job is past RunPod's retention window.", null=True),
        ),
    ]
