# Generated by Django 6.0.3 on 2026-08-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0008_externaljob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('awaiting', 'Waiting on external jobs'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('extracted', 'Extracted'), ('error', 'Error'), ('error_max_retries', 'Error (retry cap hit)'), ('error_interrupted', 'Error (interrupted too often)'), ('cancelled', 'Cancelled')], default='uploaded', max_length=20),
        ),
    ]
