# Generated by Django 6.0.3 on 2026-08-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0009_scan_awaiting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaljob',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text="Wall-clock ceiling on the state the row is in, restamped at each crossing: a queue ceiling while it waits to be submitted or picked up, and once it is running, a base timeout plus an allowance for this job's pages. Per job rather than per scan so one wedged shard is cancelled and resubmitted without stalling its siblings.", null=True),
        ),
    ]
