# Generated by Django 6.0.3 on 2026-08-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0010_alter_scan_status_awaiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('awaiting', 'Waiting on external jobs'), ('awaiting_validation', 'Awaiting Validation'), ('ready_for_page_completeness_review', 'Ready for page review'), ('page_completeness_review_done', 'Page review done'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('extracted', 'Extracted'), ('error', 'Error'), ('error_max_retries', 'Error (retry cap hit)'), ('error_interrupted', 'Error (interrupted too often)'), ('cancelled', 'Cancelled')], default='uploaded', max_length=40),
        ),
    ]
