# Generated by Django 6.0.3 on 2026-08-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0011_alter_scan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='queued_action',
            field=models.CharField(blank=True, choices=[('full_pipeline', 'Full Pipeline'), ('compute_issues', 'Compute Issues'), ('validate', 'Validate'), ('detect', 'Detect'), ('reprocess', 'Reprocess'), ('generate_files', 'Generate Files')], default='', help_text='Action for the daemon to run when status is queued.', max_length=30),
        ),
    ]
