# Generated by Django 6.0.3 on 2026-08-31 23:58

import django.db.models.deletion
import scanning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0011_alter_scan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='source_fingerprint',
            field=models.CharField(blank=True, default='', help_text="Identity of the original the pipeline last sharded: '{size_bytes}:{page_count}', the same pair the shard manifest records. Stamped by sharding.ensure_shards, and copied onto every PageEdit a curator writes (#214), so a re-cut or replaced original makes the edits written against the old one detectable rather than wrong.", max_length=64),
        ),
        migrations.CreateModel(
            name='PageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('kind', models.CharField(choices=[('set_number', 'Set the printed page number'), ('delete_page', 'Delete a page'), ('insert_page', 'Insert a page image'), ('replace_page', 'Replace a page with an image'), ('rotate_page', 'Rotate a page'), ('dismiss_issue', 'Dismiss an issue')], db_index=True, max_length=32)),
                ('pdf_page', models.PositiveIntegerField(blank=True, help_text='1-based page of the original PDF this decision is about. Set for every kind but an insert; null on a dismissal of an issue that names a printed page number or the whole volume rather than a physical page.', null=True)),
                ('anchor_pdf_page', models.PositiveIntegerField(blank=True, help_text='Inserts only: the 1-based original page the image follows. 0 puts the image before page 1.', null=True)),
                ('ordinal', models.PositiveSmallIntegerField(default=0, help_text='Inserts only: the order of several images in one gap.')),
                ('value', models.CharField(blank=True, default='', help_text="What was decided: the printed number ('1075') or range ('678-686') for a number, blank when the curator cleared it; the rotation in degrees; the dismissed check's name.", max_length=32)),
                ('replaced', models.CharField(blank=True, default='', help_text='What the decision overwrote, for the audit.', max_length=32)),
                ('logical_page', models.CharField(blank=True, default='', help_text='The printed page number this edit is about, as a label and for the audit. Never an address.', max_length=32)),
                ('image', models.FileField(blank=True, help_text='Inserts and replacements: the page the curator uploaded.', upload_to=scanning.models.page_edit_image_path)),
                ('source_fingerprint', models.CharField(blank=True, default='', help_text="The scan's source fingerprint when the decision was made. Blank on a legacy row, which matches anything.", max_length=64)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the apply (#206) built this decision into a new original. A stamped row is history: it is never rewritten.', null=True)),
                ('author', models.ForeignKey(blank=True, help_text='Who decided. Null on a row the #214 data migration wrote, since the storage it read kept no author.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_edits', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_edits', to='scanning.scan')),
            ],
            options={
                'ordering': ['scan', 'pdf_page', 'anchor_pdf_page', 'ordinal'],
                'indexes': [models.Index(fields=['scan', 'kind', 'applied_at'], name='idx_page_edit_scan_kind')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('anchor_pdf_page__isnull', False), ('kind', 'insert_page'), ('pdf_page__isnull', True)), models.Q(('anchor_pdf_page__isnull', True), ('kind', 'dismiss_issue')), models.Q(('anchor_pdf_page__isnull', True), ('kind__in', ('set_number', 'delete_page', 'replace_page', 'rotate_page')), ('pdf_page__isnull', False)), _connector='OR'), name='page_edit_address_matches_kind'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'dismiss_issue'), _negated=True), models.Q(('value', ''), _negated=True), _connector='OR'), name='page_edit_dismissal_names_a_check'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'rotate_page'), _negated=True), ('value__in', ('90', '180', '270')), _connector='OR'), name='page_edit_rotation_is_a_quarter_turn'), models.UniqueConstraint(condition=models.Q(('applied_at__isnull', True), ('pdf_page__isnull', False), models.Q(('kind', 'dismiss_issue'), _negated=True)), fields=('scan', 'kind', 'pdf_page'), name='uniq_open_page_edit_per_page'), models.UniqueConstraint(condition=models.Q(('applied_at__isnull', True), ('kind', 'dismiss_issue')), fields=('scan', 'kind', 'pdf_page', 'logical_page', 'value'), name='uniq_open_dismissal_per_check', nulls_distinct=False), models.UniqueConstraint(condition=models.Q(('applied_at__isnull', True), ('kind', 'insert_page')), fields=('scan', 'anchor_pdf_page', 'ordinal'), name='uniq_open_insert_per_gap')],
            },
        ),
    ]
