# Generated by Django 6.0.3 on 2026-09-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0013_page_edits_from_manual_readings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='check_name',
            field=models.CharField(choices=[('no_page_number', 'No page number detected'), ('missing_page', 'Missing page in sequence'), ('duplicate_page', 'Duplicate page number'), ('backward_page', 'Page number goes backward'), ('large_gap', 'Large gap in page numbers'), ('suspicious_reading', 'Suspicious OCR reading'), ('page_range', 'Page range detected'), ('mislabeled_document', 'Mislabeled document type'), ('auto_corrected', 'Auto-corrected page number'), ('blank_page', 'Blank page detected'), ('orientation', 'Page orientation issue'), ('stale_page_edit', 'Page edit not applied'), ('process_flag', 'User-flagged issue'), ('suppress_detection', 'Suppress a detection'), ('add_detection', 'Add a detection'), ('approve_detection', 'Approve a detection')], max_length=100),
        ),
    ]
