# Generated by Django 6.0.3 on 2026-09-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0016_retire_pageinsert_and_pagedeletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaljob',
            name='engine',
            field=models.CharField(choices=[('blackletter', 'blackletter (YOLO detection)'), ('bitonal', 'Bitonal conversion'), ('dots_mocr', 'dots.mocr'), ('mistral_ocr', 'Mistral OCR'), ('surya', 'Surya'), ('lighton_ocr', 'LightOnOCR')], max_length=32),
        ),
    ]
