# Generated by Django 6.0.3 on 2026-09-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0018_page_edit_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='model_name',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('bl_warm', 'bl-warm'), ('manual', 'Manual')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='queued_action',
            field=models.CharField(blank=True, choices=[('full_pipeline', 'Full Pipeline'), ('validate', 'Validate'), ('detect', 'Detect'), ('reprocess', 'Reprocess'), ('generate_files', 'Generate Files'), ('compute_redactions', 'Compute Redactions')], default='', help_text='Action for the daemon to run when status is queued.', max_length=30),
        ),
    ]
