# Generated by Django 6.0.3 on 2026-09-03 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0019_bl_warm_detections_and_compute_redactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('number', models.PositiveSmallIntegerField(help_text='The n in a{n}: 1 for the first build of this scan.')),
                ('source_fingerprint', models.CharField(blank=True, default='', help_text="The scan's source fingerprint when the run was built. Every glue checks its inputs against it.", max_length=64)),
                ('page_map', models.JSONField(blank=True, default=dict, help_text="The offset map, written once at build time: one entry per final page naming its source (an original page, with its rotation, or a page of an edit's file), plus the deleted pages and the original's page count.")),
                ('edit_ids', models.JSONField(blank=True, default=list, help_text='The standing structural PageEdit rows the build read, in primary-key order. The trigger compares it with the current set to decide whether a new run is due.')),
                ('final_pdf_key', models.CharField(blank=True, default='', help_text='S3 key of the final PDF, or of the original when no structural edit exists. Blank until the build commits.', max_length=1024)),
                ('bitonal_key', models.CharField(blank=True, default='', help_text='S3 key of the final bitonal copy. Blank until glued.', max_length=1024)),
                ('ocr_key', models.CharField(blank=True, default='', help_text='S3 key of the final OCR volume JSON. Blank until glued.', max_length=1024)),
                ('printed_pages_key', models.CharField(blank=True, default='', help_text='S3 key of the frozen printed-page map, in the final page space. Blank until the OCR glue writes it.', max_length=1024)),
                ('detections_key', models.CharField(blank=True, default='', help_text='S3 key of the final detections volume JSON. Blank until glued, which waits for a volume detection run.', max_length=1024)),
                ('built_at', models.DateTimeField(blank=True, help_text='When the final PDF, the map and the job rows were committed.', null=True)),
                ('superseded_at', models.DateTimeField(blank=True, help_text='When a later run replaced this one: the review was reopened, or an admin gave up on a dead row. Its outputs stay in S3.', null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Failed attempts at the current phase.')),
                ('last_error', models.TextField(blank=True, default='', help_text='What the last failed attempt raised.')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scan', 'number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='pageedit',
            name='uniq_open_page_edit_per_page',
        ),
        migrations.RemoveConstraint(
            model_name='pageedit',
            name='uniq_open_dismissal_per_check',
        ),
        migrations.RemoveConstraint(
            model_name='pageedit',
            name='uniq_open_insert_per_gap',
        ),
        migrations.AlterField(
            model_name='pageedit',
            name='applied_at',
            field=models.DateTimeField(blank=True, help_text='When the apply (#224) built this decision into a final volume. A ledger stamp, not a close: the row keeps standing until it is withdrawn, and it is never rewritten.', null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='queued_action',
            field=models.CharField(blank=True, choices=[('full_pipeline', 'Full Pipeline'), ('validate', 'Validate'), ('detect', 'Detect'), ('reprocess', 'Reprocess'), ('generate_files', 'Generate Files'), ('compute_redactions', 'Compute Redactions'), ('apply_page_edits', 'Apply Page Edits')], default='', help_text='Action for the daemon to run when status is queued.', max_length=30),
        ),
        migrations.AddField(
            model_name='applyrun',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_runs', to='scanning.scan'),
        ),
        migrations.AddField(
            model_name='externaljob',
            name='apply_run',
            field=models.ForeignKey(blank=True, help_text="The apply run this row works for (issue #224): a one-page shard of a page a curator added or changed. Null for the volume runs. Every reader of 'the live volume run' filters these rows out, and the apply reads its rows through this key and never by run number.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scanning.applyrun'),
        ),
        migrations.AddField(
            model_name='pageedit',
            name='applied_run',
            field=models.ForeignKey(blank=True, help_text='The apply run whose final volume carries this decision. Null while no build has read the row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_edits', to='scanning.applyrun'),
        ),
        migrations.AddConstraint(
            model_name='pageedit',
            constraint=models.UniqueConstraint(condition=models.Q(('withdrawn_at__isnull', True), ('pdf_page__isnull', False), models.Q(('kind', 'dismiss_issue'), _negated=True)), fields=('scan', 'kind', 'pdf_page'), name='uniq_standing_page_edit_per_page'),
        ),
        migrations.AddConstraint(
            model_name='pageedit',
            constraint=models.UniqueConstraint(condition=models.Q(('withdrawn_at__isnull', True), ('kind', 'dismiss_issue')), fields=('scan', 'kind', 'pdf_page', 'logical_page', 'value'), name='uniq_standing_dismissal_per_check', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='pageedit',
            constraint=models.UniqueConstraint(condition=models.Q(('withdrawn_at__isnull', True), ('kind', 'insert_page')), fields=('scan', 'anchor_pdf_page', 'ordinal'), name='uniq_standing_insert_per_gap'),
        ),
        migrations.AddConstraint(
            model_name='applyrun',
            constraint=models.UniqueConstraint(fields=('scan', 'number'), name='uniq_apply_run_number_per_scan'),
        ),
    ]
