# Generated by Django 6.0.3 on 2026-09-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0019_bl_warm_detections_and_compute_redactions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='externaljob',
            name='job_opinion_matches_stage',
        ),
        migrations.AddConstraint(
            model_name='externaljob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opinion__isnull', False), ('stage__in', ('tiebreak',))), ('stage__in', ('extract',)), models.Q(models.Q(('stage__in', ('tiebreak',)), _negated=True), models.Q(('stage__in', ('extract',)), _negated=True), ('opinion__isnull', True)), _connector='OR'), name='job_opinion_matches_stage'),
        ),
    ]
