# Generated by Django 6.0.3 on 2026-09-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0020_page_repair_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaljob',
            name='source_fingerprint',
            field=models.CharField(blank=True, default='', help_text="The shard set this row was cut for: '{size_bytes}:{page_count}' of the original, the value sharding.ensure_shards stamps on Scan.source_fingerprint. Stamped by jobs.ensure_shard_jobs on every row of every stage, so 'has this set been detected' is one query (#250). Not part of the shard identity in input_manifest. Blank on a row written before the column, which matches anything.", max_length=64),
        ),
    ]
