# Generated by Django 6.0.3 on 2026-09-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0021_external_job_source_fingerprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("awaiting", "Waiting on external jobs"),
                    ("awaiting_validation", "Awaiting Validation"),
                    (
                        "ready_for_page_completeness_review",
                        "Ready for page review",
                    ),
                    ("page_completeness_review_done", "Page review done"),
                    (
                        "ready_for_redaction_review",
                        "Ready for redaction review",
                    ),
                    ("redaction_review_done", "Redaction review done"),
                    ("pending_review", "Pending Review"),
                    ("approved", "Approved"),
                    ("extracted", "Extracted"),
                    ("error", "Error"),
                    ("error_max_retries", "Error (retry cap hit)"),
                    ("error_interrupted", "Error (interrupted too often)"),
                    ("cancelled", "Cancelled"),
                ],
                default="uploaded",
                max_length=40,
            ),
        ),
    ]
