# Generated by Django 6.0.3 on 2026-09-09 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0025_delete_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='apply_run',
            field=models.ForeignKey(blank=True, help_text="The apply run whose final page space ``page_index`` is in (#269). Null on a legacy row and on a hand-drawn row of a volume with no run: the original's space.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='scanning.applyrun'),
        ),
        migrations.AddField(
            model_name='detection',
            name='detect_run',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The detection run (``ExternalJob.run``) that found it.', null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='source_edit',
            field=models.ForeignKey(blank=True, help_text='The page edit whose one-page shard this box is on. Null means the original as uploaded (issue #240).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='scanning.pageedit'),
        ),
        migrations.AddField(
            model_name='detection',
            name='source_fingerprint',
            field=models.CharField(blank=True, default='', help_text="The scan's source fingerprint at import. Blank on a legacy row, which matches anything.", max_length=64),
        ),
        migrations.AddField(
            model_name='detection',
            name='source_page',
            field=models.PositiveIntegerField(blank=True, help_text="1-based page of the source document: of the original, or of the edit's shard. Null on a row imported before #240.", null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='Hand-drawn rows only: when the curator took the box back. The row stays; ``active`` reads False.', null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, help_text='Who took the box back. Null while it stands.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetectionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('kind', models.CharField(choices=[('approve', 'Approve (confidence 1.0)'), ('deactivate', 'Deactivate')], max_length=12)),
                ('source_page', models.PositiveIntegerField(help_text='1-based page of the source document.')),
                ('source_fingerprint', models.CharField(blank=True, default='', help_text="The scan's source fingerprint when the decision was made. Blank matches anything.", max_length=64)),
                ('label', models.CharField(max_length=50)),
                ('label_id', models.SmallIntegerField()),
                ('target_x0', models.FloatField()),
                ('target_y0', models.FloatField()),
                ('target_x1', models.FloatField()),
                ('target_y1', models.FloatField()),
                ('img_width', models.PositiveIntegerField(default=0)),
                ('img_height', models.PositiveIntegerField(default=0)),
                ('target_confidence', models.FloatField(blank=True, help_text="The model's own confidence when the decision was made, so a withdrawn approval gives it back.", null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, db_index=True, help_text='When the curator took the decision back. Never rewritten.', null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_decisions', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_decisions', to='scanning.scan')),
                ('source_edit', models.ForeignKey(blank=True, help_text='The page edit whose shard holds the page; null = the original.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_decisions', to='scanning.pageedit')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_detection_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scan', 'source_page', 'target_y0', 'target_x0'],
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='decision',
            field=models.ForeignKey(blank=True, help_text='The standing curator decision resolved onto this model row: the reason its confidence is 1.0 or it is inactive.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='scanning.detectiondecision'),
        ),
        migrations.AddField(
            model_name='detection',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='Hand-drawn rows only: the deactivation this box was drawn in place of, when a curator moved a model box.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='scanning.detectiondecision'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['scan', 'source_edit', 'source_page'], name='idx_det_scan_source'),
        ),
        migrations.AddIndex(
            model_name='detectiondecision',
            index=models.Index(fields=['scan', 'withdrawn_at'], name='idx_det_decision_scan_open'),
        ),
    ]
