"""The opinion boundaries as rows (issue #240, PR C).

``Scan.opinions_json`` held the output of the pairing as a list of
dicts with no identity and no address. ``OpinionBoundary`` replaces it,
one row per opinion and one per curator decision, and ``OpinionScan``
gets a FK to the boundary its file was cut from (#165).

**No data copy**, as decided in the plan review of 2026-09-09: the
lists were computed from the legacy YOLO trio, and the compute writes
the rows again from the current detections. What fills the table is
the collect tick: for every scan in a review the redaction compute may
be queued from (``PAGE_COMPLETENESS_REVIEW_DONE`` and
``READY_FOR_REDACTION_REVIEW``), the ``apply_run`` of the detect run's
ledger (``provider_meta["apply"]``) is blanked, so
``yolo.redactions_current`` reads "not measured against the standing
run" and ``yolo.queue_ready_runs`` queues the compute on its next tick.
The scan stays in its review throughout, and the compute writes the
boundaries, and the detections and rects again, in the measured space.
A ``REDACTION_REVIEW_DONE`` scan is left alone (#263: a closed review
is not recomputed under the person who closed it), and so is a legacy
scan, which no compute reaches.

Historical models only; the literals are the values of
``models.Status`` and the detect run's identity.
"""

# Generated by Django 6.0.3 on 2026-09-10 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

DETECT = "detect"
BLACKLETTER = "blackletter"
RUNPOD = "runpod"
RECOMPUTE_STATUSES = (
    "page_completeness_review_done",
    "ready_for_redaction_review",
)


def blank_measured_runs(apps, schema_editor):
    """Make the collect tick compute every scan in review again.

    :param apps: The historical app registry.
    :param schema_editor: Unused.
    :return: None.
    """
    ExternalJob = apps.get_model("scanning", "ExternalJob")
    heads = ExternalJob.objects.filter(
        stage=DETECT,
        engine=BLACKLETTER,
        provider=RUNPOD,
        shard_index=0,
        apply_run__isnull=True,
        provider_meta__apply__apply_run__isnull=False,
        scan__status__in=RECOMPUTE_STATUSES,
    )
    for head in heads:
        meta = dict(head.provider_meta or {})
        state = dict(meta.get("apply") or {})
        state.pop("apply_run", None)
        meta["apply"] = state
        head.provider_meta = meta
        head.save(update_fields=["provider_meta"])


class Migration(migrations.Migration):
    dependencies = [
        ("scanning", "0026_detection_decisions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scan",
            name="opinions_json",
        ),
        migrations.CreateModel(
            name="OpinionBoundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("computed", "Computed by the pairing"),
                            ("human", "Made by a curator"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("add", "A boundary the curator added"),
                            (
                                "dismiss",
                                "A computed boundary the curator dismissed",
                            ),
                        ],
                        default="",
                        help_text="Human rows only; blank on a computed row.",
                        max_length=10,
                    ),
                ),
                (
                    "start_source_page",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="1-based page of the start's source document. Null when the map held no address for the page at write time.",
                        null=True,
                    ),
                ),
                (
                    "start_page_index",
                    models.PositiveIntegerField(
                        help_text="0-based page of the start, in the space of ``apply_run``."
                    ),
                ),
                (
                    "start_x",
                    models.FloatField(
                        help_text="PDF points: the caption's left."
                    ),
                ),
                (
                    "start_y",
                    models.FloatField(
                        help_text="PDF points: the caption's top."
                    ),
                ),
                (
                    "end_source_page",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="As ``start_source_page``, for the end page.",
                        null=True,
                    ),
                ),
                (
                    "end_page_index",
                    models.PositiveIntegerField(
                        help_text="0-based page of the end, in the space of ``apply_run``."
                    ),
                ),
                (
                    "end_x",
                    models.FloatField(
                        help_text="PDF points: the key icon's right."
                    ),
                ),
                (
                    "end_y",
                    models.FloatField(
                        help_text="PDF points: the key icon's bottom."
                    ),
                ),
                (
                    "source_fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The scan's source fingerprint when the row was written. Blank matches anything (the #214 rule).",
                        max_length=64,
                    ),
                ),
                (
                    "detect_run",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Computed rows: the detection run (``ExternalJob.run``) the pairing read.",
                        null=True,
                    ),
                ),
                (
                    "ordinal",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Computed rows: the position the pairing gave the opinion, 0-based, in reading order. Null on a human row.",
                        null=True,
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Human rows only: when the curator took the row back. Never rewritten.",
                        null=True,
                    ),
                ),
                (
                    "apply_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="The apply run whose final page space the two indexes are in (#269). Null for the original's space.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opinion_boundaries",
                        to="scanning.applyrun",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Human rows: the curator.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opinion_boundaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        help_text="Computed rows: the standing dismissal resolved onto this row. Null while the boundary stands.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_boundaries",
                        to="scanning.opinionboundary",
                    ),
                ),
                (
                    "end_detection",
                    models.ForeignKey(
                        blank=True,
                        help_text="The key icon row the end anchor was taken from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opinion_ends",
                        to="scanning.detection",
                    ),
                ),
                (
                    "end_source_edit",
                    models.ForeignKey(
                        blank=True,
                        help_text="As ``start_source_edit``, for the end page.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boundary_ends",
                        to="scanning.pageedit",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        help_text="Additions only: the dismissal this boundary was made in place of, when a curator moved an anchor.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacements",
                        to="scanning.opinionboundary",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinion_boundaries",
                        to="scanning.scan",
                    ),
                ),
                (
                    "start_detection",
                    models.ForeignKey(
                        blank=True,
                        help_text="The caption row the start anchor was taken from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opinion_starts",
                        to="scanning.detection",
                    ),
                ),
                (
                    "start_source_edit",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page edit whose shard holds the start page; null = the original as uploaded.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boundary_starts",
                        to="scanning.pageedit",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who took the row back. Null while it stands.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawn_opinion_boundaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scan", "start_page_index", "start_y", "start_x"],
            },
        ),
        migrations.AddField(
            model_name="opinionscan",
            name="boundary",
            field=models.ForeignKey(
                blank=True,
                help_text="The review-2 boundary this file was cut from (issue #240, PR C). Step 3 sets it when it creates the row; a computed boundary is rebuilt at each compute, so the link stands only while the boundary row does (#165).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opinion_scans",
                to="scanning.opinionboundary",
            ),
        ),
        migrations.AddIndex(
            model_name="opinionboundary",
            index=models.Index(
                fields=["scan", "origin", "withdrawn_at"],
                name="idx_opb_scan_open",
            ),
        ),
        migrations.AddIndex(
            model_name="opinionboundary",
            index=models.Index(
                fields=["scan", "start_source_edit", "start_source_page"],
                name="idx_opb_scan_start_source",
            ),
        ),
        migrations.AddIndex(
            model_name="opinionboundary",
            index=models.Index(
                fields=["scan", "start_page_index"],
                name="idx_opb_scan_start_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinionboundary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", ""), ("origin", "computed")),
                    models.Q(
                        ("kind__in", ["add", "dismiss"]), ("origin", "human")
                    ),
                    _connector="OR",
                ),
                name="opinion_boundary_kind_matches_origin",
            ),
        ),
        migrations.RunPython(blank_measured_runs, migrations.RunPython.noop),
    ]
