"""One ``Redaction`` table replaces the two rect blobs (issue #240, PR B).

No data is copied: the blobs came from the legacy YOLO trio, and the
compute writes the rows again. For every scan in review 2's two open
statuses the detect ledger's ``apply_run`` is blanked, so the collect
tick (``yolo.queue_ready_runs``) sees the redactions as not current and
queues the compute, which writes the rows within minutes. A closed
review (``REDACTION_REVIEW_DONE``) is not recomputed under the person
who closed it (#263), and a legacy volume has no run: both get no rows.
"""

# Generated by Django 6.0.3 on 2026-09-10 02:39

import logging

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

#: The statuses the redaction compute may be queued from
#: (``yolo.APPLY_STATUSES``), inlined so the migration does not import
#: the app.
_APPLY_STATUSES = (
    "page_completeness_review_done",
    "ready_for_redaction_review",
)


def blank_redaction_ledgers(apps, schema_editor):
    """Make every scan in review 2 owe a redaction compute.

    :param apps: The historical app registry.
    :param schema_editor: Unused.
    :return: None.
    """
    ExternalJob = apps.get_model("scanning", "ExternalJob")
    heads = ExternalJob.objects.filter(
        stage="detect",
        engine="blackletter",
        provider="runpod",
        shard_index=0,
        apply_run__isnull=True,
        scan__status__in=_APPLY_STATUSES,
        provider_meta__apply__apply_run__isnull=False,
    )
    blanked = 0
    for head in heads:
        meta = dict(head.provider_meta or {})
        state = dict(meta.get("apply") or {})
        if state.get("apply_run") is None:
            continue
        state.pop("apply_run", None)
        meta["apply"] = state
        head.provider_meta = meta
        head.save(update_fields=["provider_meta"])
        blanked += 1
    Scan = apps.get_model("scanning", "Scan")
    closed = Scan.objects.filter(status="redaction_review_done").count()
    logging.getLogger(__name__).info(
        "redaction ledgers blanked: %d; closed reviews left without rows: %d",
        blanked,
        closed,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("scanning", "0027_opinion_boundaries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            blank_redaction_ledgers, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="scan",
            name="margin_rects",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="redaction_rects",
        ),
        migrations.CreateModel(
            name="Redaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("computed", "Computed"), ("human", "Human")],
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("add", "Add a box"),
                            ("dismiss", "Dismiss a computed box"),
                        ],
                        default="",
                        help_text="Human rows only; blank on a computed row.",
                        max_length=10,
                    ),
                ),
                (
                    "rect_type",
                    models.CharField(
                        help_text="blackletter's type of the box (headnote, a label name, ...), 'margin' for a strip, 'manual' for a drawn box.",
                        max_length=50,
                    ),
                ),
                (
                    "fill",
                    models.CharField(
                        choices=[("black", "Black"), ("white", "White")],
                        max_length=5,
                    ),
                ),
                ("x0", models.FloatField(blank=True, null=True)),
                ("y0", models.FloatField(blank=True, null=True)),
                ("x1", models.FloatField(blank=True, null=True)),
                ("y1", models.FloatField(blank=True, null=True)),
                ("target_x0", models.FloatField(blank=True, null=True)),
                ("target_y0", models.FloatField(blank=True, null=True)),
                ("target_x1", models.FloatField(blank=True, null=True)),
                ("target_y1", models.FloatField(blank=True, null=True)),
                (
                    "source_page",
                    models.PositiveIntegerField(
                        help_text="1-based page of the source document."
                    ),
                ),
                (
                    "source_fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The scan's source fingerprint when the row was written.",
                        max_length=64,
                    ),
                ),
                (
                    "page_index",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="0-based position in the space of ``apply_run``.",
                    ),
                ),
                (
                    "detect_run",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Computed rows: the detection run the geometry came from.",
                        null=True,
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Human rows: when the curator took the row back.",
                        null=True,
                    ),
                ),
                (
                    "apply_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="The apply run whose final page space ``page_index`` is in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redactions",
                        to="scanning.applyrun",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        help_text="Computed rows: the standing dismiss resolved onto this box, which hides it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided",
                        to="scanning.redaction",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        help_text="Adds only: the dismiss this box was drawn in place of, when a curator moved a computed box.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacements",
                        to="scanning.redaction",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redactions",
                        to="scanning.scan",
                    ),
                ),
                (
                    "source_edit",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page edit whose shard holds the page; null = the original.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redactions",
                        to="scanning.pageedit",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawn_redactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scan", "page_index", "y0", "x0"],
                "indexes": [
                    models.Index(
                        fields=["scan", "page_index"],
                        name="idx_redaction_scan_page",
                    ),
                    models.Index(
                        fields=["scan", "source_edit", "source_page"],
                        name="idx_redaction_scan_source",
                    ),
                    models.Index(
                        fields=["scan", "origin", "withdrawn_at"],
                        name="idx_redaction_scan_open",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", ""), ("origin", "computed")),
                            models.Q(
                                ("kind__in", ["add", "dismiss"]),
                                ("origin", "human"),
                            ),
                            _connector="OR",
                        ),
                        name="redaction_kind_matches_origin",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="opinionboundary",
            name="uncovered_page_indexes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "The pages of this opinion, in the space of ``apply_run``, "
                    "with a confident HEADNOTE box no headnote rect covers. "
                    "Stamped by the redaction compute (#240 PR B), which measures "
                    "it in the render's pixels where the detections and the "
                    "rects both are; a request cannot, since the redaction rows "
                    "are in points. PR D makes it a finding."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="redaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kind", "add"), ("withdrawn_at__isnull", True)
                ),
                fields=("replaces",),
                name="uniq_standing_replacement_per_dismiss",
            ),
        ),
    ]
