# Generated by Django 6.0.3 on 2026-09-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0029_review2_findings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaljob",
            name="engine",
            field=models.CharField(
                choices=[
                    ("blackletter", "blackletter (YOLO detection)"),
                    ("bitonal", "Bitonal conversion"),
                    ("dots_mocr", "dots.mocr"),
                    ("caselaw_tagger", "caselaw-block-tagger"),
                    ("mistral_ocr", "Mistral OCR"),
                    ("surya", "Surya"),
                    ("lighton_ocr", "LightOnOCR"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="externaljob",
            name="stage",
            field=models.CharField(
                choices=[
                    ("convert", "Convert to bitonal"),
                    ("detect", "Detect (YOLO)"),
                    ("analyze", "Analyze (page numbers)"),
                    ("tag", "Tag (case-law blocks)"),
                    ("extract", "Extract text"),
                    ("tiebreak", "Tiebreak disputed reads"),
                ],
                max_length=20,
            ),
        ),
    ]
