# Generated by Django 6.0.3 on 2026-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0029_review2_findings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageedit',
            name='value',
            field=models.CharField(blank=True, default='', help_text="What was decided: the printed number ('1075'), the number with a trailing letter ('2094a') or the range ('678-686') for a number, blank when the curator cleared it; the rotation in degrees; the dismissed check's name.", max_length=32),
        ),
    ]
