# Generated by Django 6.0.3 on 2026-09-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0030_alter_pageedit_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='check_name',
            field=models.CharField(choices=[('no_page_number', 'No page number detected'), ('missing_page', 'Missing page in sequence'), ('duplicate_page', 'Duplicate page number'), ('backward_page', 'Page number goes backward'), ('large_gap', 'Large gap in page numbers'), ('suspicious_reading', 'Suspicious OCR reading'), ('page_range', 'Page range detected'), ('mislabeled_document', 'Mislabeled document type'), ('auto_corrected', 'Auto-corrected page number'), ('blank_page', 'Blank page detected'), ('orientation', 'Page orientation issue'), ('stale_page_edit', 'Page edit not applied'), ('process_flag', 'User-flagged issue'), ('unmatched_key_icon', 'Key icon not matched to an opinion'), ('unmatched_caption', 'Caption not matched to an opinion'), ('uncovered_pages', 'Pages not covered by an opinion'), ('uncovered_headnote', 'Headnote not covered by a redaction'), ('missing_headnote_bracket', 'Headnote bracket the model did not find'), ('stale_detection_edit', 'Detection decision not applied'), ('stale_redaction_edit', 'Redaction decision not applied'), ('stale_boundary_edit', 'Opinion boundary decision not applied')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewdismissal',
            name='check_name',
            field=models.CharField(choices=[('unmatched_key_icon', 'Key icon not matched to an opinion'), ('unmatched_caption', 'Caption not matched to an opinion'), ('uncovered_pages', 'Pages not covered by an opinion'), ('uncovered_headnote', 'Headnote not covered by a redaction'), ('missing_headnote_bracket', 'Headnote bracket the model did not find')], max_length=100),
        ),
        migrations.CreateModel(
            name='BracketReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('source_page', models.PositiveIntegerField(blank=True, help_text='1-based page of the source document.', null=True)),
                ('source_fingerprint', models.CharField(blank=True, default='', help_text="The scan's source fingerprint when the reading was written. Blank matches anything.", max_length=64)),
                ('page_index', models.PositiveIntegerField(db_index=True)),
                ('x0', models.FloatField()),
                ('y0', models.FloatField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('img_width', models.PositiveIntegerField(default=0)),
                ('img_height', models.PositiveIntegerField(default=0)),
                ('numbers', models.JSONField(default=list, help_text='The headnote numbers the bracket names, expanded: ``[16-19]`` is stored as ``[16, 17, 18, 19]``.')),
                ('raw', models.CharField(help_text='The token as dots.mocr wrote it, for the card.', max_length=32)),
                ('apply_run', models.ForeignKey(blank=True, help_text="The apply run whose page space ``page_index`` is in. Null means the original's space.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket_readings', to='scanning.applyrun')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_readings', to='scanning.scan')),
                ('source_edit', models.ForeignKey(blank=True, help_text='The page edit whose one-page shard this cell is on. Null means the original as uploaded.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket_readings', to='scanning.pageedit')),
            ],
            options={
                'ordering': ['page_index', 'y0', 'x0'],
                'indexes': [models.Index(fields=['scan', 'apply_run', 'page_index'], name='idx_bracket_scan_run_page')],
            },
        ),
    ]
