# Generated by Django 6.0.3 on 2026-09-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanning", "0032_extract_stage_either_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyrun",
            name="extract_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "S3 key of the final Mistral OCR volume JSON (#245). "
                    "Blank until glued, which waits for a Mistral volume "
                    "run, and a volume nobody read with Mistral never has "
                    "one. No review state reads it."
                ),
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="applyrun",
            name="extract_run",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "The Mistral volume run extract_key was glued from. A "
                    "second read of the volume gets a later run number, and "
                    "that is what makes the glue due again."
                ),
                null=True,
            ),
        ),
    ]
