# Generated by Django 6.0.3 on 2026-09-16 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0033_apply_run_extract_outputs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinionscan',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_opinions', to='scanning.scan'),
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('first_printed_page', models.PositiveIntegerField(help_text='The printed number of the page the opinion starts on, as stamped at creation. Half of the identity.')),
                ('index_in_page', models.PositiveSmallIntegerField(default=0, help_text='The rank of the opinion among those that start on that printed page, in reading order. 0 for the first. The other half of the identity.')),
                ('last_printed_page', models.PositiveIntegerField(help_text='The printed number of the last page. Feeds the gap check.')),
                ('page_count', models.PositiveIntegerField(help_text='The true count of physical pages, so no check does arithmetic on the printed numbers. A page with a trailing letter (#319) counts here and names no printed number.')),
                ('start_source_page', models.PositiveIntegerField(blank=True, help_text="1-based page of the first page's source document.", null=True)),
                ('end_source_page', models.PositiveIntegerField(blank=True, help_text='As ``start_source_page``, for the last page.', null=True)),
                ('start_page_index', models.PositiveIntegerField(help_text='0-based first page, in the space of ``apply_run``.')),
                ('end_page_index', models.PositiveIntegerField(help_text='0-based last page, in the space of ``apply_run``.')),
                ('source_fingerprint', models.CharField(blank=True, default='', help_text="The scan's source fingerprint when the row was written. Blank matches anything (the #214 rule).", max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready_for_text_review', 'Ready for text review'), ('text_review_done', 'Text review done'), ('error', 'Error')], db_index=True, default='processing', max_length=25)),
                ('error_message', models.TextField(blank=True, default='', help_text='What failed in the work that prepares the review.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('glue_revision', models.PositiveSmallIntegerField(default=0, help_text='The revision of the per-opinion glues. Every glue key is derived from the pk and this number; a re-glue raises it.')),
                ('approved_text_key', models.CharField(blank=True, default='', help_text='S3 key of the text written once at the approval, the frozen output the tagger reads (#272). Not a glue.', max_length=512)),
                ('notes', models.TextField(blank=True, default='')),
                ('apply_run', models.ForeignKey(blank=True, help_text="The apply run whose page space the two indexes are in (#269). Null for the original's space.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinions', to='scanning.applyrun')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opinions', to=settings.AUTH_USER_MODEL)),
                ('boundary', models.ForeignKey(blank=True, help_text='The boundary the opinion was cut from, for the viewer. Not the identity: a computed boundary is rebuilt at every compute, so this link stands only while that row does.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinions', to='scanning.opinionboundary')),
                ('end_source_edit', models.ForeignKey(blank=True, help_text='As ``start_source_edit``, for the last page.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinion_ends', to='scanning.pageedit')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='scanning.scan')),
                ('start_source_edit', models.ForeignKey(blank=True, help_text='The page edit whose one-page shard holds the first page; null = the original as uploaded.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinion_starts', to='scanning.pageedit')),
            ],
            options={
                'ordering': ['first_printed_page', 'index_in_page'],
            },
        ),
        migrations.AlterField(
            model_name='externaljob',
            name='opinion',
            field=models.ForeignKey(blank=True, help_text='The opinion this job worked on, for the opinion-level stages. Null for the volume-level stages, which run before any opinion exists. Must belong to ``scan``.\n\nCASCADE rather than SET_NULL: an orphaned row would break the invariant that an opinion-level stage has an opinion, and would leave the stage barrier counting a row with no target. An ``Opinion`` is keyed by its printed page and survives a re-glue (#335), so a CASCADE here no longer throws away paid work at every regenerate, which is what #165 raised against ``OpinionScan``.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scanning.opinion'),
        ),
        migrations.CreateModel(
            name='OpinionFindingDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('page_in_opinion', models.PositiveSmallIntegerField(blank=True, help_text='Null when the finding is about the whole opinion.', null=True)),
                ('check_name', models.CharField(choices=[('engines_disagree', 'The engines do not all agree'), ('no_majority', 'No two engines agree'), ('reading_order', 'The reading order needs a check'), ('column_edge', 'A column starts or ends here'), ('partial_redaction', 'A redaction covers part of a cell'), ('page_gap', 'A gap in the printed page numbers')], max_length=50)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinion_finding_dismissals', to=settings.AUTH_USER_MODEL)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_dismissals', to='scanning.opinion')),
            ],
        ),
        migrations.CreateModel(
            name='OpinionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('page_in_opinion', models.PositiveSmallIntegerField(blank=True, help_text='Null when the finding is about the whole opinion.', null=True)),
                ('check_name', models.CharField(choices=[('engines_disagree', 'The engines do not all agree'), ('no_majority', 'No two engines agree'), ('reading_order', 'The reading order needs a check'), ('column_edge', 'A column starts or ends here'), ('partial_redaction', 'A redaction covers part of a cell'), ('page_gap', 'A gap in the printed page numbers'), ('stale_page_number', 'The printed number changed'), ('orphaned_opinion', 'No boundary matches this opinion')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanning.opinion')),
                ('dismissal', models.ForeignKey(blank=True, help_text='Set by the rebuild when a standing dismissal names it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='scanning.opinionfindingdismissal')),
            ],
            options={
                'ordering': ['page_in_opinion', 'check_name'],
            },
        ),
        migrations.CreateModel(
            name='OpinionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('page_in_opinion', models.PositiveSmallIntegerField(help_text='0-based page of the opinion. Half of the identity.')),
                ('source_page', models.PositiveIntegerField(blank=True, help_text='1-based page of the source document.', null=True)),
                ('page_index', models.PositiveIntegerField(help_text='0-based page of the volume, in the space of ``apply_run``.')),
                ('text', models.TextField(blank=True, default='', help_text='The resolved text of the page, in reading order. A cache, rebuilt from the glued runs plus the human rows.')),
                ('disagreements', models.JSONField(blank=True, default=list, help_text="One entry per place the engines differ: ``{'start': int, 'end': int, 'variants': {engine: text}}``, with the offsets against ``text``. Empty when they agree.")),
                ('human_text', models.TextField(blank=True, default='', help_text='What a curator typed. Never discarded.')),
                ('human_at', models.DateTimeField(blank=True, null=True)),
                ('apply_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinion_pages', to='scanning.applyrun')),
                ('human_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinion_page_edits', to=settings.AUTH_USER_MODEL)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='scanning.opinion')),
                ('source_edit', models.ForeignKey(blank=True, help_text='The durable address in the volume; null = the original.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinion_pages', to='scanning.pageedit')),
            ],
            options={
                'ordering': ['page_in_opinion'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawnOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('first_printed_page', models.PositiveIntegerField()),
                ('last_printed_page', models.PositiveIntegerField()),
                ('source_page', models.PositiveIntegerField(blank=True, help_text="1-based page of the notice page's source document.", null=True)),
                ('page_index', models.PositiveIntegerField(help_text='0-based notice page, in the space of ``apply_run``.')),
                ('source_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='', help_text='What the book says about the withdrawal.')),
                ('notice_pdf_key', models.CharField(blank=True, default='', help_text='S3 key of the PDF of the notice page.', max_length=512)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('apply_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_opinions', to='scanning.applyrun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_opinions', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawn_opinions', to='scanning.scan')),
                ('source_edit', models.ForeignKey(blank=True, help_text='The page edit whose shard holds the notice page.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawn_opinions', to='scanning.pageedit')),
            ],
            options={
                'ordering': ['first_printed_page'],
            },
        ),
        migrations.AddIndex(
            model_name='opinion',
            index=models.Index(fields=['scan', 'status'], name='idx_opinion_review_status'),
        ),
        migrations.AddConstraint(
            model_name='opinion',
            constraint=models.UniqueConstraint(fields=('scan', 'first_printed_page', 'index_in_page'), name='unique_opinion_per_printed_page'),
        ),
        migrations.AddConstraint(
            model_name='opinion',
            constraint=models.CheckConstraint(condition=models.Q(('first_printed_page__lte', models.F('last_printed_page'))), name='opinion_printed_pages_ordered'),
        ),
        migrations.AddConstraint(
            model_name='opinionfindingdismissal',
            constraint=models.UniqueConstraint(condition=models.Q(('page_in_opinion__isnull', False), ('withdrawn_at__isnull', True)), fields=('opinion', 'page_in_opinion', 'check_name'), name='unique_standing_page_dismissal'),
        ),
        migrations.AddConstraint(
            model_name='opinionfindingdismissal',
            constraint=models.UniqueConstraint(condition=models.Q(('page_in_opinion__isnull', True), ('withdrawn_at__isnull', True)), fields=('opinion', 'check_name'), name='unique_standing_opinion_dismissal'),
        ),
        migrations.AddIndex(
            model_name='opinionfinding',
            index=models.Index(fields=['opinion', 'check_name'], name='idx_opinion_finding'),
        ),
        migrations.AddConstraint(
            model_name='opiniontext',
            constraint=models.UniqueConstraint(fields=('opinion', 'page_in_opinion'), name='unique_opinion_page'),
        ),
        migrations.AddIndex(
            model_name='withdrawnopinion',
            index=models.Index(fields=['scan', 'first_printed_page'], name='idx_withdrawn_scan_page'),
        ),
        migrations.AddConstraint(
            model_name='withdrawnopinion',
            constraint=models.CheckConstraint(condition=models.Q(('first_printed_page__lte', models.F('last_printed_page'))), name='withdrawn_printed_pages_ordered'),
        ),
    ]
