# Generated by Django 6.0.3 on 2026-09-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0034_opinion_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='queued_action',
            field=models.CharField(blank=True, choices=[('full_pipeline', 'Full Pipeline'), ('validate', 'Validate'), ('detect', 'Detect'), ('reprocess', 'Reprocess'), ('generate_files', 'Generate Files'), ('compute_redactions', 'Compute Redactions'), ('apply_page_edits', 'Apply Page Edits'), ('create_opinions', 'Create Opinions')], default='', help_text='Action for the daemon to run when status is queued.', max_length=30),
        ),
    ]
