# Generated by Django 6.0.3 on 2026-09-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0039_apply_run_surya_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='ensemble_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Failed ensemble ticks on this row at the live revision (#365). At ensemble.MAX_ATTEMPTS the row goes to ERROR.'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='ensemble_revision',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The ocr_glue_revision the ensemble ran at (#365). Equal to ocr_glue_revision: the text of the rows describes the OCR documents that exist now, the one rule ensemble.is_written reads.', null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='ocr_engine_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many engine documents the OCR glue wrote at ocr_glue_revision (#365). The ensemble gate reads it, so a two-engine volume waits for the third engine.'),
        ),
    ]
