# Generated by Django 6.0.3 on 2026-09-19 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0041_page_not_read_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pageedit',
            name='page_edit_address_matches_kind',
        ),
        migrations.AlterField(
            model_name='pageedit',
            name='anchor_pdf_page',
            field=models.PositiveIntegerField(blank=True, help_text='Inserts and moves: the 1-based original page the image, or the moved page, follows. 0 puts it before page 1.', null=True),
        ),
        migrations.AlterField(
            model_name='pageedit',
            name='kind',
            field=models.CharField(choices=[('set_number', 'Set the printed page number'), ('delete_page', 'Delete a page'), ('insert_page', 'Insert a page image'), ('replace_page', 'Replace a page with an image'), ('rotate_page', 'Rotate a page'), ('move_page', 'Move a page to another place'), ('dismiss_issue', 'Dismiss an issue')], db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='pageedit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anchor_pdf_page__isnull', False), ('kind', 'insert_page'), ('pdf_page__isnull', True)), models.Q(('anchor_pdf_page__isnull', False), ('kind', 'move_page'), ('pdf_page__isnull', False)), models.Q(('anchor_pdf_page__isnull', True), ('kind', 'dismiss_issue')), models.Q(('anchor_pdf_page__isnull', True), ('kind__in', ('set_number', 'delete_page', 'replace_page', 'rotate_page')), ('pdf_page__isnull', False)), _connector='OR'), name='page_edit_address_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='pageedit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'move_page'), _negated=True), models.Q(('anchor_pdf_page', models.F('pdf_page')), _negated=True), _connector='OR'), name='page_edit_move_leaves_its_page'),
        ),
    ]
