# Generated by Django 6.0.3 on 2026-09-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0042_page_edit_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiniontext',
            name='footnotes',
            field=models.TextField(blank=True, default='', help_text="The resolved text of the page's footnotes, in reading order (#399). A cache like ``text``, and never a part of it: the tagger reads ``text`` alone. The ``footnotes`` entries of ``disagreements`` point into this field."),
        ),
        migrations.AlterField(
            model_name='opinionfinding',
            name='check_name',
            field=models.CharField(choices=[('engines_disagree', 'The engines do not all agree'), ('no_majority', 'No two engines agree'), ('reading_order', 'The reading order needs a check'), ('column_edge', 'A column starts or ends here'), ('partial_redaction', 'A redaction covers part of a cell'), ('page_not_read', 'This page has no text'), ('footnote_unsure', 'An engine read a footnote no detection covers'), ('page_gap', 'A gap in the printed page numbers'), ('stale_page_number', 'The printed number changed'), ('orphaned_opinion', 'No boundary matches this opinion')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='opinionfindingdismissal',
            name='check_name',
            field=models.CharField(choices=[('engines_disagree', 'The engines do not all agree'), ('no_majority', 'No two engines agree'), ('reading_order', 'The reading order needs a check'), ('column_edge', 'A column starts or ends here'), ('partial_redaction', 'A redaction covers part of a cell'), ('page_not_read', 'This page has no text'), ('footnote_unsure', 'An engine read a footnote no detection covers'), ('page_gap', 'A gap in the printed page numbers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='opiniontext',
            name='disagreements',
            field=models.JSONField(blank=True, default=list, help_text="One entry per place the engines differ: ``{'start': int, 'end': int, 'section': 'text' | 'footnotes', 'variants': {engine: text}}``, with the offsets against the field ``section`` names. Empty when they agree."),
        ),
    ]
