# Generated by Django 6.0.3 on 2026-09-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0042_page_edit_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageedit',
            name='ordinal',
            field=models.PositiveSmallIntegerField(default=0, help_text='Inserts and moves: the order of several images in one gap, or of several moved pages landing on one anchor.'),
        ),
    ]
