# Generated by Django 6.0.3 on 2026-09-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0044_low_confidence_headnote_bracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiniontext',
            name='marks',
            field=models.JSONField(blank=True, default=list, help_text="The formatting the engines read (#404): ``{'start': int, 'end': int, 'kind': 'em' | 'strong' | 'sup', 'section': 'text' | 'footnotes'}``, with the offsets against the field ``section`` names. A cache like ``text``, and of ``text``: an edit of ``human_text`` moves every offset."),
        ),
    ]
