# Generated by Django 6.0.3 on 2026-09-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0045_opinion_text_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinionfinding',
            name='check_name',
            field=models.CharField(choices=[('engines_disagree', 'The engines do not all agree'), ('no_majority', 'No two engines agree'), ('reading_order', 'The reading order needs a check'), ('column_edge', 'A column starts or ends here'), ('partial_redaction', 'A redaction covers part of a cell'), ('page_not_read', 'This page has no text'), ('footnote_unsure', 'An engine read a footnote no detection covers'), ('blockquote_list', 'A blockquote may be a list'), ('page_gap', 'A gap in the printed page numbers'), ('stale_page_number', 'The printed number changed'), ('orphaned_opinion', 'No boundary matches this opinion')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='opinionfindingdismissal',
            name='check_name',
            field=models.CharField(choices=[('engines_disagree', 'The engines do not all agree'), ('no_majority', 'No two engines agree'), ('reading_order', 'The reading order needs a check'), ('column_edge', 'A column starts or ends here'), ('partial_redaction', 'A redaction covers part of a cell'), ('page_not_read', 'This page has no text'), ('footnote_unsure', 'An engine read a footnote no detection covers'), ('blockquote_list', 'A blockquote may be a list'), ('page_gap', 'A gap in the printed page numbers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='opiniontext',
            name='marks',
            field=models.JSONField(blank=True, default=list, help_text="The formatting the engines read (#404): ``{'start': int, 'end': int, 'kind': 'em' | 'strong' | 'sup' | 'blockquote', 'section': 'text' | 'footnotes'}``, with the offsets against the field ``section`` names. A ``blockquote`` mark spans one run of quoted groups of the body (#411). A cache like ``text``, and of ``text``: an edit of ``human_text`` moves every offset."),
        ),
    ]
