# Generated by Django 6.0.3 on 2026-09-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0046_blockquote_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinionfinding',
            name='check_name',
            field=models.CharField(choices=[('engines_disagree', 'The engines do not all agree'), ('no_majority', 'No two engines agree on a block'), ('single_engine', 'One engine alone read a block'), ('reading_order', 'The reading order needs a check'), ('column_edge', 'A column starts or ends here'), ('partial_redaction', 'A redaction covers part of a cell'), ('page_not_read', 'This page has no text'), ('footnote_unsure', 'An engine read a footnote no detection covers'), ('blockquote_list', 'A blockquote may be a list'), ('page_gap', 'A gap in the printed page numbers'), ('stale_page_number', 'The printed number changed'), ('orphaned_opinion', 'No boundary matches this opinion')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='opinionfindingdismissal',
            name='check_name',
            field=models.CharField(choices=[('engines_disagree', 'The engines do not all agree'), ('no_majority', 'No two engines agree on a block'), ('single_engine', 'One engine alone read a block'), ('reading_order', 'The reading order needs a check'), ('column_edge', 'A column starts or ends here'), ('partial_redaction', 'A redaction covers part of a cell'), ('page_not_read', 'This page has no text'), ('footnote_unsure', 'An engine read a footnote no detection covers'), ('blockquote_list', 'A blockquote may be a list'), ('page_gap', 'A gap in the printed page numbers')], max_length=50),
        ),
    ]
