# Generated by Django 6.0.3 on 2026-09-25 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0047_opinion_check_single_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='edit_revision',
            field=models.PositiveIntegerField(default=0, help_text='Raised by every write of an OpinionEdit row (#376), in the transaction of the write. The ensemble reads it before it reads the edits.'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='ensemble_edit_revision',
            field=models.PositiveIntegerField(default=0, help_text="The edit_revision the ensemble document was built at (#376). It names the document's key, so no two builds write one key, and a reader presigns the key of this number."),
        ),
        migrations.AlterField(
            model_name='opinionfinding',
            name='check_name',
            field=models.CharField(choices=[('engines_disagree', 'The engines do not all agree'), ('no_majority', 'No two engines agree on a block'), ('single_engine', 'One engine alone read a block'), ('reading_order', 'The reading order needs a check'), ('column_edge', 'A column starts or ends here'), ('partial_redaction', 'A redaction covers part of a cell'), ('page_not_read', 'This page has no text'), ('footnote_unsure', 'An engine read a footnote no detection covers'), ('blockquote_list', 'A blockquote may be a list'), ('page_gap', 'A gap in the printed page numbers'), ('stale_page_number', 'The printed number changed'), ('orphaned_opinion', 'No boundary matches this opinion'), ('unresolved_edit', 'A human edit no longer fits the text')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='OpinionEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('kind', models.CharField(choices=[('text', 'Text of a block'), ('section', 'Section of a block'), ('order', 'Order of the blocks of a page')], max_length=10)),
                ('source_page', models.PositiveIntegerField(blank=True, help_text='1-based page of the source document.', null=True)),
                ('page_in_opinion', models.PositiveSmallIntegerField(help_text='A copy for the display. The address decides.')),
                ('box_pt', models.JSONField(blank=True, help_text="TEXT and SECTION: a copy of the block's box, in the points of the volume page.", null=True)),
                ('section', models.CharField(blank=True, default='', help_text='TEXT: the section the block was in. SECTION: the new section. ORDER: the section the order is of.', max_length=10)),
                ('base_text', models.TextField(blank=True, default='', help_text='TEXT: the text the curator saw.')),
                ('text', models.TextField(blank=True, default='', help_text="TEXT: the new text, folded like an engine's.")),
                ('order', models.JSONField(blank=True, help_text='ORDER: the box copies of the section, in the new order.', null=True)),
                ('glue_revision', models.PositiveSmallIntegerField(help_text='The glue revision the curator saw.')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinion_edits', to=settings.AUTH_USER_MODEL)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='scanning.opinion')),
                ('replaces', models.ForeignKey(blank=True, help_text='The standing row this row superseded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='scanning.opinionedit')),
                ('source_edit', models.ForeignKey(blank=True, help_text='The durable address of the page; null = the original.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinion_edits', to='scanning.pageedit')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_opinion_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['opinion', 'withdrawn_at'], name='idx_opinion_edit_standing')],
            },
        ),
    ]
