# Generated by Django 6.0.3 on 2026-09-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0048_opinion_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinionedit',
            name='quoted',
            field=models.BooleanField(blank=True, help_text='BLOCKQUOTE: true for a blockquote, false for no blockquote.', null=True),
        ),
        migrations.AddField(
            model_name='opinionedit',
            name='span',
            field=models.JSONField(blank=True, help_text='BLOCKQUOTE: [start, end] of the quoted text in base_text; null = the whole block.', null=True),
        ),
        migrations.AlterField(
            model_name='opinionedit',
            name='base_text',
            field=models.TextField(blank=True, default='', help_text='TEXT, and BLOCKQUOTE with a span: the text the curator saw.'),
        ),
        migrations.AlterField(
            model_name='opinionedit',
            name='kind',
            field=models.CharField(choices=[('text', 'Text of a block'), ('section', 'Section of a block'), ('order', 'Order of the blocks of a page'), ('blockquote', 'Blockquote of a block')], max_length=10),
        ),
    ]
