# Generated by Django 6.0.3 on 2026-09-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0049_opinion_edit_blockquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniontext',
            name='marks',
            field=models.JSONField(blank=True, default=list, help_text="The formatting the engines read (#404): ``{'start': int, 'end': int, 'kind': 'em' | 'strong' | 'sup' | 'blockquote' | 'ul' | 'ol' | 'li', 'section': 'text' | 'footnotes'}``, with the offsets against the field ``section`` names. A ``blockquote`` mark spans one run of quoted groups of the body (#411), a ``ul`` or ``ol`` mark one run of list groups, and an ``li`` mark one item of a list (#428). A cache like ``text``, and of ``text``: an edit of ``human_text`` moves every offset."),
        ),
    ]
