# Generated by Django 6.0.3 on 2026-09-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0050_opinion_text_list_marks'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='externaljob',
            name='job_opinion_matches_stage',
        ),
        migrations.AddField(
            model_name='opinion',
            name='tag_key',
            field=models.CharField(blank=True, default='', help_text="S3 key of the tagger's spans over the approved text (#272), written by ``tagger.glue_run``. Blank until a run is glued.", max_length=512),
        ),
        migrations.AddField(
            model_name='opinion',
            name='tagged_text_key',
            field=models.CharField(blank=True, default='', help_text='The ``approved_text_key`` the spans at ``tag_key`` were computed over. The spans are current when the two keys are equal (``tagger.is_written``).', max_length=512),
        ),
        migrations.AlterField(
            model_name='externaljob',
            name='engine',
            field=models.CharField(choices=[('blackletter', 'blackletter (YOLO detection)'), ('bitonal', 'Bitonal conversion'), ('dots_mocr', 'dots.mocr'), ('caselaw_tagger', 'caselaw-block-tagger'), ('mistral_ocr', 'Mistral OCR'), ('surya', 'Surya'), ('lighton_ocr', 'LightOnOCR')], max_length=32),
        ),
        migrations.AlterField(
            model_name='externaljob',
            name='stage',
            field=models.CharField(choices=[('convert', 'Convert to bitonal'), ('detect', 'Detect (YOLO)'), ('analyze', 'Analyze (page numbers)'), ('tag', 'Tag (case-law blocks)'), ('extract', 'Extract text'), ('tiebreak', 'Tiebreak disputed reads')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='externaljob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opinion__isnull', False), ('stage__in', ('tiebreak', 'tag'))), ('stage__in', ('extract',)), models.Q(models.Q(('stage__in', ('tiebreak', 'tag')), _negated=True), models.Q(('stage__in', ('extract',)), _negated=True), ('opinion__isnull', True)), _connector='OR'), name='job_opinion_matches_stage'),
        ),
    ]
