# Generated by Django 6.0.3 on 2026-09-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0051_caselaw_tagger_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='final_xml_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Failed exports of the final XML that the objects explain (#408); a transient S3 fault counts none. Reset when the spans are placed again and when the export is written.'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='final_xml_schema',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The ``casebody.SCHEMA`` the exported final XML was built with (#408). Null: no object is stored.', null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='final_xml_tag_key',
            field=models.CharField(blank=True, default='', help_text='The ``tag_key`` the exported final XML was built from (#408), at ``final-xml/{scan}/{opinion}.xml``. Blank: no object is stored. The export is current when it equals ``tag_key`` and ``final_xml_schema`` is ``casebody.SCHEMA`` (``final_xml.is_written``).', max_length=512),
        ),
    ]
