# Generated by Django 6.0.3 on 2026-10-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanning", "0051_caselaw_tagger_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="page_scores",
            field=models.JSONField(
                blank=True,
                help_text="The bad-page model's score of every page of the review-1 bitonal copy, keyed by the 1-based original page, with the model version and the source fingerprint it was measured under. Written by badpage.scoring.stamp; read through badpage.scoring.scores_of, which drops a stamp made against another upload. Null until a volume is scored.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="check_name",
            field=models.CharField(
                choices=[
                    ("no_page_number", "No page number detected"),
                    ("front_matter", "Unnumbered pages at the front"),
                    ("missing_page", "Missing page in sequence"),
                    ("duplicate_page", "Duplicate page number"),
                    ("backward_page", "Page number goes backward"),
                    ("large_gap", "Large gap in page numbers"),
                    ("suspicious_reading", "Suspicious OCR reading"),
                    ("bad_page", "Possible bad scan"),
                    ("page_range", "Page range detected"),
                    ("mislabeled_document", "Mislabeled document type"),
                    ("auto_corrected", "Auto-corrected page number"),
                    ("blank_page", "Blank page detected"),
                    ("orientation", "Page orientation issue"),
                    ("stale_page_edit", "Page edit not applied"),
                    ("process_flag", "User-flagged issue"),
                    (
                        "unmatched_key_icon",
                        "Key icon not matched to an opinion",
                    ),
                    ("unmatched_caption", "Caption not matched to an opinion"),
                    ("uncovered_pages", "Pages not covered by an opinion"),
                    (
                        "uncovered_headnote",
                        "Headnote not covered by a redaction",
                    ),
                    (
                        "missing_headnote_bracket",
                        "Headnote bracket the model did not find",
                    ),
                    (
                        "low_confidence_headnote_bracket",
                        "Headnote bracket under the redaction gate",
                    ),
                    ("stale_detection_edit", "Detection decision not applied"),
                    ("stale_redaction_edit", "Redaction decision not applied"),
                    (
                        "stale_boundary_edit",
                        "Opinion boundary decision not applied",
                    ),
                ],
                max_length=100,
            ),
        ),
    ]
