# Generated by Django 6.0.3 on 2026-10-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanning", "0054_editorialreading"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinion",
            name="figure_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Failed cuts of this row's pictures that the rows explain (#463). At opinion_figures.MAX_ATTEMPTS the row goes to ERROR.",
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="figure_digest",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A digest of the pictures of the ensemble document (#463), stamped by the ensemble: blank when the text holds none.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="figures_attempted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the cut of this row's pictures last failed, of either kind (#463). The row is not due again before opinion_pdf.retry_after() has passed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="figures_cut_digest",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The figure_digest the pictures were cut at (#463). Equal to figure_digest, or a blank figure_digest: every picture is cut, the one rule opinion_figures.is_written reads.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="opinionfinding",
            name="check_name",
            field=models.CharField(
                choices=[
                    ("engines_disagree", "The engines do not all agree"),
                    ("no_majority", "No two engines agree on a block"),
                    ("single_engine", "One engine alone read a block"),
                    ("reading_order", "The reading order needs a check"),
                    ("column_edge", "A column starts or ends here"),
                    ("partial_redaction", "A redaction covers part of a cell"),
                    ("page_not_read", "This page has no text"),
                    (
                        "footnote_unsure",
                        "An engine read a footnote no detection covers",
                    ),
                    ("blockquote_list", "A blockquote may be a list"),
                    ("page_gap", "A gap in the printed page numbers"),
                    ("stale_page_number", "The printed number changed"),
                    ("orphaned_opinion", "No boundary matches this opinion"),
                    (
                        "unresolved_edit",
                        "A human edit no longer fits the text",
                    ),
                    ("figure_one_engine", "One engine alone drew a picture"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opinionfindingdismissal",
            name="check_name",
            field=models.CharField(
                choices=[
                    ("engines_disagree", "The engines do not all agree"),
                    ("no_majority", "No two engines agree on a block"),
                    ("single_engine", "One engine alone read a block"),
                    ("reading_order", "The reading order needs a check"),
                    ("column_edge", "A column starts or ends here"),
                    ("partial_redaction", "A redaction covers part of a cell"),
                    ("page_not_read", "This page has no text"),
                    (
                        "footnote_unsure",
                        "An engine read a footnote no detection covers",
                    ),
                    ("blockquote_list", "A blockquote may be a list"),
                    ("page_gap", "A gap in the printed page numbers"),
                    ("figure_one_engine", "One engine alone drew a picture"),
                ],
                max_length=50,
            ),
        ),
    ]
