# Generated by Django 6.0.3 on 2026-10-07 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanning", "0054_editorialreading"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinionfinding",
            name="check_name",
            field=models.CharField(
                choices=[
                    ("engines_disagree", "The engines do not all agree"),
                    ("no_majority", "No two engines agree on a block"),
                    ("single_engine", "One engine alone read a block"),
                    ("reading_order", "The reading order needs a check"),
                    ("column_edge", "A column starts or ends here"),
                    ("partial_redaction", "A redaction covers part of a cell"),
                    ("page_not_read", "This page has no text"),
                    (
                        "footnote_unsure",
                        "An engine read a footnote no detection covers",
                    ),
                    ("blockquote_list", "A blockquote may be a list"),
                    ("page_gap", "A gap in the printed page numbers"),
                    ("stale_page_number", "The printed number changed"),
                    ("orphaned_opinion", "No boundary matches this opinion"),
                    (
                        "unresolved_edit",
                        "A human edit no longer fits the text",
                    ),
                    (
                        "shared_footnotes",
                        "Footnotes of a page shared with the opinion before",
                    ),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opinionfindingdismissal",
            name="check_name",
            field=models.CharField(
                choices=[
                    ("engines_disagree", "The engines do not all agree"),
                    ("no_majority", "No two engines agree on a block"),
                    ("single_engine", "One engine alone read a block"),
                    ("reading_order", "The reading order needs a check"),
                    ("column_edge", "A column starts or ends here"),
                    ("partial_redaction", "A redaction covers part of a cell"),
                    ("page_not_read", "This page has no text"),
                    (
                        "footnote_unsure",
                        "An engine read a footnote no detection covers",
                    ),
                    ("blockquote_list", "A blockquote may be a list"),
                    ("page_gap", "A gap in the printed page numbers"),
                    (
                        "shared_footnotes",
                        "Footnotes of a page shared with the opinion before",
                    ),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="KeptFootnotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified.",
                    ),
                ),
                (
                    "source_page",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="1-based page of the source document.",
                        null=True,
                    ),
                ),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kept_footnotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opinion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kept_footnotes",
                        to="scanning.opinion",
                    ),
                ),
                (
                    "source_edit",
                    models.ForeignKey(
                        blank=True,
                        help_text="The durable address of the page; null = the original.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kept_footnotes",
                        to="scanning.pageedit",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawn_kept_footnotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("withdrawn_at__isnull", True)),
                        fields=("opinion",),
                        name="unique_standing_kept_footnotes",
                    )
                ],
            },
        ),
    ]
