# Generated by Django 6.0.3 on 2026-10-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanning", "0055_opinion_final_xml_export"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinionedit",
            name="box_pt",
            field=models.JSONField(
                blank=True,
                help_text="TEXT, SECTION, BLOCKQUOTE and DROP: a copy of the block's box, in the points of the volume page.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="opinionedit",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Text of a block"),
                    ("section", "Section of a block"),
                    ("order", "Order of the blocks of a page"),
                    ("blockquote", "Blockquote of a block"),
                    ("drop", "Block that is not text"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="opinionfinding",
            name="check_name",
            field=models.CharField(
                choices=[
                    ("engines_disagree", "The engines do not all agree"),
                    ("no_majority", "No two engines agree on a block"),
                    ("single_engine", "One engine alone read a block"),
                    ("reading_order", "The reading order needs a check"),
                    ("column_edge", "A column starts or ends here"),
                    ("partial_redaction", "A redaction covers part of a cell"),
                    (
                        "undetected_text",
                        "Text where the detections drew nothing",
                    ),
                    ("page_not_read", "This page has no text"),
                    (
                        "footnote_unsure",
                        "An engine read a footnote no detection covers",
                    ),
                    ("blockquote_list", "A blockquote may be a list"),
                    ("page_gap", "A gap in the printed page numbers"),
                    ("stale_page_number", "The printed number changed"),
                    ("orphaned_opinion", "No boundary matches this opinion"),
                    (
                        "unresolved_edit",
                        "A human edit no longer fits the text",
                    ),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opinionfindingdismissal",
            name="check_name",
            field=models.CharField(
                choices=[
                    ("engines_disagree", "The engines do not all agree"),
                    ("no_majority", "No two engines agree on a block"),
                    ("single_engine", "One engine alone read a block"),
                    ("reading_order", "The reading order needs a check"),
                    ("column_edge", "A column starts or ends here"),
                    ("partial_redaction", "A redaction covers part of a cell"),
                    (
                        "undetected_text",
                        "Text where the detections drew nothing",
                    ),
                    ("page_not_read", "This page has no text"),
                    (
                        "footnote_unsure",
                        "An engine read a footnote no detection covers",
                    ),
                    ("blockquote_list", "A blockquote may be a list"),
                    ("page_gap", "A gap in the printed page numbers"),
                ],
                max_length=50,
            ),
        ),
    ]
