# Generated by Django 6.0.3 on 2026-05-14 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('prompt_type', models.SmallIntegerField(choices=[(1, 'System'), (2, 'User')], default=1)),
                ('text', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
            },
        ),
        migrations.CreateModel(
            name='LLMBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_batch', models.BooleanField(default=False)),
                ('batch_id', models.CharField(blank=True, max_length=255)),
                ('provider', models.SmallIntegerField(choices=[(1, 'Google Gemini'), (2, 'OpenAI'), (3, 'Anthropic')], default=1)),
                ('api_model_name', models.CharField(blank=True, max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, 'Unprocessed'), (1, 'In Progress'), (2, 'LLM response received'), (3, 'Failed'), (4, 'LLM response processed')], default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('failed_tasks', models.IntegerField(default=0)),
                ('max_retries', models.SmallIntegerField(default=3)),
                ('total_cost_estimate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total_cost_actual', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('extra_config_params', models.JSONField(blank=True, default=dict)),
                ('batch_response_file', models.FileField(blank=True, max_length=1000, upload_to='llm_requests/')),
                ('prompts', models.ManyToManyField(blank=True, related_name='requests', to='ai.prompt')),
            ],
            options={
                'verbose_name': 'LLM Request',
                'verbose_name_plural': 'LLM Requests',
            },
        ),
        migrations.CreateModel(
            name='LLMTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified.')),
                ('status', models.SmallIntegerField(choices=[(0, 'Unprocessed'), (1, 'In Progress'), (2, 'LLM response received'), (3, 'Failed'), (4, 'LLM response processed')], default=0)),
                ('llm_key', models.CharField(max_length=255)),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('input_file', models.FileField(blank=True, max_length=1000, upload_to='llm_tasks/inputs/')),
                ('input_text', models.TextField(blank=True)),
                ('response_file', models.FileField(blank=True, max_length=1000, upload_to='llm_tasks/responses/')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ai.llmbatch')),
            ],
            options={
                'verbose_name': 'LLM Task',
                'verbose_name_plural': 'LLM Tasks',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='ai_llmtask_content_49d7d1_idx')],
            },
        ),
    ]
