---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanning-web
  namespace: scanning
  labels:
    service: scanning-web
spec:
  replicas: 2
  selector:
    matchLabels:
      service: scanning-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        service: scanning-web
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: spots-node-group-v7
      containers:
        - name: web
          image: freelawproject/scanning:7b1d7c8-prod
          args: ["web-prod"]
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: scanning-env
          env:
            - name: PGAPPNAME
              value: scanning-web
          startupProbe:
            initialDelaySeconds: 30
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 30
            httpGet:
              path: /monitoring/heartbeat/
              port: 8000
              scheme: HTTP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 10
            exec:
              command:
                # See: https://github.com/benoitc/gunicorn/issues/2467#issuecomment-738378167
                - /opt/venv/bin/python
                - -c
                - |
                  import socket
                  s = socket.socket()
                  s.settimeout(1)
                  s.connect(("localhost", 8000))
          resources:
            requests:
              memory: 500Mi
            limits:
              memory: 500Mi
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: scanning-web
  namespace: scanning
  labels:
    service: scanning-web
spec:
  selector:
    service: scanning-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanning-daemon
  namespace: scanning
  labels:
    service: scanning-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      service: scanning-daemon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: scanning-daemon
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: spots-node-group-v7
      containers:
        - name: scanning-daemon
          image: freelawproject/scanning:7b1d7c8-prod
          args: ["run_daemon"]
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: scanning-env
          env:
            - name: PGAPPNAME
              value: scanning-daemon